### ISSUE TITLE
[Question ] How do we compare with mih?

### ISSUE THREAD

**Issue by posix4e** [facebookresearch/faiss#1078]
Recently we've been on the hunt for the best exact nn search algorithms. So far the big ones we wanna benchmark are y'all and MIH

1. What other ones would you like us to benchmark?
2. What's the best source for production code nn search benchmarks?
3. Have y'all already benchmarked vs MIH?

**Comment by wickedfoo** [comment]
You mean binary vector exact search (e.g., binary multi-index hashing is what you mean by MIH)?

I guess Faiss binary exact search (IndexBinaryFlat, GpuIndexBinaryFlat) is different than MIH, and has slightly different use cases.

MIH requires a search radius and the cost of the query is dependent upon that while Faiss, which is completely brute force, does not. Faiss will of course traverse a lot more memory when doing a query (it really is brute-force) and be way slower, though it won't duplicate IDs in different buckets, the storage is just the cost of the bits and the IDs.

Faiss is primarily oriented around batch queries (e.g., query the k=50 nearest neighbors for 10,000 vectors against a billion vectors in a single go) rather than query sizes of 1; e.g., for computing k-NN graphs and such things. MIH might with high probability end up touching all of the buckets when doing such a batch query and could very well be slower for large batches.

For a batch size of 1 MIH would always win I would think except in extremely small datasets.

I would be curious to compare MIH against brute-force IndexBinaryFlat / GpuIndexBinaryFlat as a function of batch size (which I guess without more clever implementations would involve calling MIH query iteratively for each query in the batch) to see if there is a crossover point where batch brute-force is faster.

**Comment by posix4e** [comment]
Yep binary multi-index hashing is what you mean by MIH)

**Comment by mdouze** [comment]
The index most similar to multi-index hashing is `IndexBinaryIVF`.  We have not compared it with multi-index hashing because we focus on memory-efficient indexing and MIH tends to require a lot of indexes to handle large search radiuses. 

It would be interesting to do some comparions though, feel free to post any findings you have here!

**Comment by mdouze** [comment]
No activtiy, closing.
