### ISSUE TITLE
C API Features

### ISSUE THREAD

**Issue by ankane** [facebookresearch/faiss#1133]
Hi, I recently tried out the C API. It's really well-designed and easy to follow. I was wondering if there are plans to add more features. A few that seem to be missing are:

- Binary indexes (`IndexBinaryFlat`, `IndexBinaryIVF`, `index_binary_factory`)
- `IndexHNSWFlat`
- `IndexPQ`, `IndexIVFPQ`, and `IndexIVFPQR`
- `PCAMatrix`
- `ProductQuantizer`

**Comment by mdouze** [comment]
The C API is not maintained by Facebook. 
Maybe @Enet4 could reply to these questions?

**Comment by Enet4** [comment]
Thank you for reaching out. Originally, I implemented this API in order to have a better integration with my own data processing tools in my PhD. While I intend to maintain this API and the faiss-rs library for as long as I can, there are no plans on my end to add the missing pieces.

With that said, if there is something you'd like to become available via this API, I would be glad to provide some guidance.

**Comment by ankane** [comment]
Thank you both for the response and context. It sounds like it's better to use the C++ API when possible, so will continue with that for the Ruby library.
