### ISSUE TITLE
index.search includes self?

### ISSUE THREAD

**Issue by lobpcg** [facebookresearch/faiss#1143]
# Summary

index.search includes the trivial self

# Platform

OS: Colab

Faiss version: faiss-1.5.3 faiss-gpu-1.6.1

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

!apt install libomp-dev
!python -m pip install --upgrade faiss faiss-gpu
import faiss
from numpy import arange

x = arange(8).reshape(4, 2).astype('float32')
m_size = x.shape[1]
index = faiss.IndexFlatL2(m_size)
index.add(x)
D, I = index.search(x, 2);
print(I)
print(D)

[[0 1]
 [1 0]
 [2 1]
 [3 2]]
[[0. 8.]
 [0. 8.]
 [0. 8.]
 [0. 8.]]

I.e. the index includes self, and the distance includes zero, just wasting memory.
Is this normal/anticipated?

**Comment by Enet4** [comment]
Yes, the search function does not treat a vector that is equal to the query vector as an exception. I believe it to be better that way, considering that not all use cases involve taking indexed vectors as the query (so discarding the alleged "self" could indeed be undesirable), and the logic for discarding exactly equal vectors might also be too expensive or unreliable due to numerical instability.

**Comment by lobpcg** [comment]
Thanks for your prompt reply! Closing.
