### ISSUE TITLE
index.is_trained() is False after I transfered the index to GPU and trained it

### ISSUE THREAD

**Issue by baker221** [facebookresearch/faiss#1412]
# Summary

I build a IVFFlat Model and transfer it to my GPUs, then I trained the model. The assertation of the index has been trained failed.
# Platform

OS: Ubuntu 18.04

Faiss version: 1.6.3

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
My code:
```Python3
    nlist = 100
    quantizer = faiss.IndexFlatL2(d)
    cpu_index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
    assert not cpu_index.is_trained
    ngpus = faiss.get_num_gpus()
    print("number of GPUs:", ngpus)
    gpu_index = faiss.index_cpu_to_all_gpus(cpu_index)
    gpu_index.train(xb)
    assert gpu_index.is_trained
    gpu_index.add(xb)
```
The second assertation failed.

**Comment by mdouze** [comment]
How many GPUs do you have?

**Comment by baker221** [comment]
3

**Comment by wickedfoo** [comment]
I have found the issue, IndexReplicas does not set the is_trained flag upon training, will send out a diff.

However, because this is a replicated index (not a sharded index) on multiple GPUs, you are in effect passing the same data to each of the GPU replicas, doing N times the work for no reason. For a replicated index, one should train the index on a single GPU or on the CPU, then create the replica.

**Comment by igattm** [comment]
Hello! I recently installed faiss with the following specs:
OS: Ubuntu 18.04.5 LTS

Faiss version: 1.6.3

Installed from: anaconda

I have several GPU cards installed on a machine. Could you please provide a simple example code for training IVFPQ index on one or several GPUs, and then synchronizing them on all GPUs?

Right now I'm training faiss on CPU and then copy trained IVFPQ index on all gpus using index_cpu_to_all_gpus, but I would like to train faster.
