### ISSUE TITLE
is there any way to self-search a ivfpq index?

### ISSUE THREAD

**Issue by onriv** [facebookresearch/faiss#1427]
I got a IndexIVFPQ file, and currently for some reason I wanna self-search the vectors in the index itself. And unfortunately the index file are generated via `add_with_ids` method, otherwise I would just reconstruct the vector and self-search itself. So is it any way I can self-search a ivfpq index, or just search with codes rather than vector? I wanna avoid scanning the original vectors database, it's too huge.

Maybe the problems is that i can't reconstruct vector from the index file (for it's not seuquential ids).

**Comment by mdouze** [comment]
It is not possible to search by code, because the query-side vectors are not encoded. 
What is possible is to reconstruct an approximation of the vectors and use that approximation as query vectors: 
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#direct-map-for-an-indexivf

**Comment by onriv** [comment]
Thank you very much. I got it now
