### ISSUE TITLE
Question: Search Nearest Neighboring Group of Vectors

### ISSUE THREAD

**Issue by tim-hilt** [facebookresearch/faiss#1442]
# Summary

I regard FAISS as a promising library to do nearest neighbor search on a database of extracted feature-vectors, but don't know how i should get started

# Platform

OS: Arch Linux

```
~ λ uname -r
5.8.12-arch1-1
```

Faiss version: master

Faiss compilation options: none

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

# Issue/Question

Hi there! I'm in the process of building an object-retrieval system. Here's what i currently do for testing and evaluation:

1. Extract features for all images in training-database
    - 1000 images present
    - Extracting 5000 descriptor-vectors per image, each having binary structure with a length of 256Bit (ORB)
    - Result is a vector of dim 5000 x 256 x 1000 (num features x len descriptor x num images)
2. Extract features of query image (dim: 5000 features x 256 bit)
3. Find best matching descriptor-matrix from training-database
    - Done using BFMatcher from OpenCV
    - Takes **forever** to compute because it does linear comparison of all descriptor-vectors based on Hamming-Distance

So basically i have to perform a search for the best fitting 2d-matrix among the elements of a 3d-matrix.

Looking at FAISS it seems like it would be able to speed up the search considerably, however, i don't know how to search for the "best matching group of vectors", although i have the feeling FAISS would be able to do this. There has already been some discussion about similar issues/questions in #27 and #1000 . Following up the last issue there has been [a GitHub-Repo published that implements my approach for a single image-pair](https://github.com/ryanfb/skimage-orbs-faiss-example), however that doesn't help me much. Also the benchmark [Indexing 1G vectors](https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors) is performed on SIFT-descriptors, which seems to be related.

Other approaches i see would be to use Bag-of-Visual-Keypoints (as implemented in [DBoW2](https://github.com/dorian3d/DBoW2) or [OpenCV](https://docs.opencv.org/master/de/d24/group__features2d__category.html)) or Deep-Learning approaches as mentioned in #27 .

Could someone help me in getting into this issue? Also, if FAISS is **not** the right tool or if you know better approaches than the ones listed above, i would be highly interested in hearing why and what.

Thanks in advance for every response to this issue!

**Comment by tim-hilt** [comment]
Is it possible to just use the descriptors extracted from a query-image and match them against a database with "unordered descriptors" and without grouping them particularily? Looking at [the wiki on Binary indexes](https://github.com/facebookresearch/faiss/wiki/Binary-indexes) that seems to be the case!

**Comment by MichaelMai2000** [comment]
I am not an expert in the field of CV, but I am doing my own project on CBIR right now. I think ORB algorithm would give multiple (assume 5000) binary descriptors for one single input image. And to create a cross match, a BFMatcher would check 5000*5000 match, then gives the best match.
Note that the 5000 descriptors for a single image are independent (if my understanding on ORB is correct), so the order of each descriptor in the list of all descriptors from one image doesn't matter. (That is, the rank of descriptor in a returned tuple doesn't contain any information.) In your words, descriptors are unordered.
To use FAISS speeding up the matching process, I think it is possible to have only one index holding flatten ORB descriptors of 1000 images. The solution that comes to my mind is: We prepare the training set: a list  (length 1000 * 5000) of vectors (256) and keep the grouping information, saying the rank of descriptors to be indexed holds the information of which image it comes from. (Unordered among one image, ordered across all images to be queried.) You could query 500 descriptors and get the best match indexes in the training set, then divide them by 5000 so that you know which picture in the training set has been matched. As a result, you have a list of indexes of pictures, and you can pick the index that occurs most frequently to be your match.

**Comment by tim-hilt** [comment]
> Note that the 5000 descriptors for a single image are independent (if my understanding on ORB is correct), so the order of each descriptor in the list of all descriptors from one image doesn't matter.

Yes, that's my impression also. The different keypoints have a `.response`-attribute that holds the strongness of the keypoint, however i would face object alterations in between matches, so that the strong features aren't present anymore. Because of that i don't care for the response that much. The vast majority of my matches are already pretty weak but i'm evaluating recall as (number of good matches)/(number of possible matches).

> I think it is possible to have only one index holding flatten ORB descriptors of 1000 images. The solution that comes to my mind is: We prepare the training set: a list (length 1000 * 5000) of vectors (256) and keep the grouping information, saying the rank of descriptors to be indexed holds the information of which image it comes from.

I think i've lost you there. Can you explain your idea simpler? In the meantime i found [this blogpost that uses `add_with__ids`](https://waltyou.github.io/Faiss-In-Project-English/). Could this be the solution you're describing?

**Comment by MichaelMai2000** [comment]
I am sorry if my explanation is confusing, but basically the idea was identical to `add_with_ids`.

**Comment by tim-hilt** [comment]
Thanks for the feedback! I think, i'll try that!
