### ISSUE TITLE
Size limit of faiss index

### ISSUE THREAD

**Issue by s252805** [facebookresearch/faiss#1444]
I have a very big dataset (almost 10^8 vectors) of high dimensionality (256) vectors. Given that I'm using an IndexIVFFlat, I saw that an index with 10^6 vectors takes about 10GB of memory, so I'm estimating that the whole index will be about 1TB of memory. I want to fit the whole index in RAM, for fast retrieval, and I need to buy hardware for the task. 
I was wondering, does it make sense to store everything in one huge (~1TB) index provided that I have enough RAM or are there hard limits to an index's size? Is it better to keep many smaller sized indexes? Or is it better to split the index across a few servers (as described in the tutorial about distributed index)?

**Comment by wickedfoo** [comment]
As long as the indexing arithmetic for the data fits within an int64_t, it should be fine (on the GPU this restriction is int32_t).

Note that IVFFlat is already an approximate index due to the IVF partitioning, it is effectively a collection of sub-indexes and won't produce the exact result. As far as memory is concerned, you need not split it into separate indexes yourself. Since you are dealing with an approximate index anyways, you could consider other compression techniques such as dimensionality reduction (e.g., PCA) and product quantization (IndexIVFPQ) to significantly reduce the memory size of this.

I guess it is up to you to decide the memory size vs. speed vs. quality of result tradeoff that is appropriate for your use case.

**Comment by mdouze** [comment]
See also https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index

**Comment by s252805** [comment]
Thank you both for the quick responses.
The original vectors have much higher dimensionality (2^15) and I already reduced them to 256 with PCA, therefore reducing them further (with PCA or product quantization) would decrease accuracy too much. 
Good to know that indexes do not have a fixed size limit.
What about the number of cores? Ideally, I would imagine that for a big number of queries having 128 cores should be about 10x faster than having 12 cores, is this correct? Is there any limit to the number of cores used during index.search()? Is the speed increase inversely proportional to the number of cores?

**Comment by wickedfoo** [comment]
IVFFlat will likely be largely memory bandwidth bound as it involves a lot of list scanning with little arithmetic done per each entry. There will be decreasing speedup with more cores, as they are all contending for DRAM accesses.

The number of cores used is controlled by OpenMP configuration.

**Comment by s252805** [comment]
Thank you for your kindness
