### ISSUE TITLE
GPU Memory Usage Increase Adding Vectors To IVF Index

### ISSUE THREAD

**Issue by kevinchevalier** [facebookresearch/faiss#1448]
# Summary

From v1.5.3 to v1.6.3, GPU memory usage has increased when adding vectors to an IVF index, and then never querying.  In v1.5.3 GPU memory use was constant.  Now it grows linearly with number of vectors.

We used the following steps to decrease our index build time from 6 hours to 90 minutes for adding 60M vectors:

- Load empty trained IVF index.
- Convert to GPU Index.
- Load all vectors into index.
- Convert to CPU Index.
- Write index to file.

Previously, this took constant GPU memory, but now GPU memory usage increases linearly until the GPU runs out of memory and the process crashes.

# Platform

Faiss version: v1.6.3

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

The following Python script will train an index and add vectors.  GPU memory usage is constant for v1.5.3 and grows linearly with vectors added in v1.6.3.

```
import faiss
import numpy as np
import GPUtil


d = 144
m = 8
nlist = 65000

# Get GPU resources                                                                                                                                                                  
res = faiss.StandardGpuResources()

quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFScalarQuantizer(quantizer, d, nlist, faiss.ScalarQuantizer.QT_8bit)

xb = np.random.randn(1000000, 144).astype('float32')
gpu_index = faiss.index_cpu_to_gpu(res, 0, index)
gpu_index.train(xb)

print('Memory used after training', GPUtil.getGPUs()[0].memoryUsed)
for n in range(65):
    xb = np.random.randn(1000000, 144).astype('float32')
    print(f'Memory Used Just Before Adding 1M vectors {n} times:', GPUtil.getGPUs()[0].memoryUsed)
    gpu_index.add(xb)
```

## Output v1.5.3

```
WARNING clustering 1000000 points to 65000 centroids: please provide at least 2535000 training points
Memory used after training 1677.0
Memory Used Just Before Adding 1M vectors 0 times: 1677.0
Memory Used Just Before Adding 1M vectors 1 times: 1677.0
Memory Used Just Before Adding 1M vectors 2 times: 1677.0
Memory Used Just Before Adding 1M vectors 3 times: 1677.0
Memory Used Just Before Adding 1M vectors 4 times: 1677.0
Memory Used Just Before Adding 1M vectors 5 times: 1677.0
Memory Used Just Before Adding 1M vectors6 times: 1677.0
...
```

## Output v1.6.3

```
WARNING clustering 1000000 points to 65000 centroids: please provide at least 2535000 training points
Memory used after training 1676.0
Memory Used Just Before Adding 1M vectors 0 times: 1676.0
Memory Used Just Before Adding 1M vectors 1 times: 1911.0
Memory Used Just Before Adding 1M vectors 2 times: 2135.0
Memory Used Just Before Adding 1M vectors 3 times: 2372.0
Memory Used Just Before Adding 1M vectors 4 times: 2579.0
...
```

## Conda Environments

```
name: faiss-1.5.3
channels:
  - pytorch
dependencies:
  - python=3.7
  - faiss-cpu=1.5.3
  - faiss-gpu=1.5.3
  - pip
  - pip:
    - GPUtil
```

```
name: faiss-1.6.3
channels:
  - pytorch
dependencies:
  - python=3.7
  - faiss-cpu=1.6.3
  - faiss-gpu=1.6.3
  - pip
  - pip:
    - GPUtil
```

**Comment by wickedfoo** [comment]
In 1.5.3 the GPU memory wasn't growing because the GPU wasn't being used for the index, there was no GPU version of the IVFScalarQuantizer in 1.5.3, so it was just using the CPU version.

The 1.6.3 version is the expected behavior here, 1000000 x 144 x sizeof(char) is the memory which is being added to the IVF lists each time, and the IVF lists overprovision themselves based on what is being added (much like dynamically growing arrays do in various programming languages, like `std::vector<>` in C++ for instance), so more than 144 MB would typically be allocated. To shrink the index to the exact size needed, `reclaimIndex()` on the GPU index instance can be called

https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/GpuIndexIVFScalarQuantizer.h#L62

Also, typically the behavior is better / it is more efficient (less overprovisioning etc) if you pass all the vectors you want to add to the GPU in larger blocks or even as one big block, instead of calling add() multiple times, as it has to reallocate IVF lists, append to new ones, delete old ones and the like.

**Comment by wickedfoo** [comment]
FYI you can construct the GPU index directly so you know what you're going to get:

```
res = faiss.StandardGpuResources()
index = faiss.GpuIndexIVFScalarQuantizer(res, d, nlist, faiss.ScalarQuantizer.QT_8bit)
index.train(...)
index.add(...)
```
