### ISSUE TITLE
About compressing the vector for inner product search

### ISSUE THREAD

**Issue by mrcsunshine** [facebookresearch/faiss#152]
Hi,
 I want to use IndexIVFQA to scale up to very large datasets , and the searching method is cos similarity. But I got an error when I set the quantizer as IndexFlatIP. There any way to compress the vector for inner product search? 

The codes  and errors are as follow: 
quantizer = faiss.IndexFlatIP(d)  # this remains the same
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)

IndexIVFPQ::precompute_table: WARN precomputed tables not supported for inner product quantizers

**Comment by mdouze** [comment]
Hi 

1. when searching with cosine distance, L2 and IP are equivalent because they operate on normalized vectors.
2. you are getting a warning, not an error, so IP search it should still work.

**Comment by mrcsunshine** [comment]
The formula of Cosine similarity is x1*x2/|x1|*|x2|=x1norm*x2norm
And for L2 is (x1-x2)^2=x1-2*x1norm*x2norm+x2

Although the vector of x1 x2 is divided by |x1|,|x2| as x1norm and x2norm, there is still x1,x2 left in L2. 
Can u help to explain why they are equivalent? Thx so much

**Comment by seanchung2** [comment]
Hi I'd wonder what do you mean by **1. when searching with cosine distance, L2 and IP are equivalent because they operate on normalized vectors.**

To be specific, if I am doing cosine similarity, do you mean I can safely use
`index = faiss.index_factory(DIMENSION, "IVF65536_HNSW32,Flat")` ?
Do I need to first do 2nd-order normalization on my vectors beforehand?
