### ISSUE TITLE
[Question][Range Search]How distance is calculated in case INNER_PRODUCT metric is used and inner product is negative

### ISSUE THREAD

**Issue by yana2301** [facebookresearch/faiss#1674]
I'm using 'IVF100,Flat' index with INNER_PRODUCT metric. I noticed that when I search data using range_search method, negative distances are never returned. However, in general, dot product may be negative. 
How Faiss calculates the distance in case the dot product is negative?

**Comment by mdouze** [comment]
There is no special handling for negative values, so they can be returned:

https://gist.github.com/mdouze/134953f0433f3474014388c103a96920

Note that since you are using INNER_PRODUCT metric, the elements *above* a threshold are returned, so to get negative results, the threshold should be negative as in the example above.
