### ISSUE TITLE
FAISS 1.7 replaced sync_with_shard_indexes with syncWithSubIndexes?

### ISSUE THREAD

**Issue by okhat** [facebookresearch/faiss#1702]
It appears that faiss 1.7 replaced `sync_with_shard_indexes` with `syncWithSubIndexes` for multi-GPU sharded indexes. Is this right? If so, the example [here](https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_1bn.py) does not seem to have been updated.

Are there any changes in functionality we need to keep in mind?

# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [x ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Good catch! 
This is because this diff

https://github.com/facebookresearch/faiss/commit/ef6e53f8ba6b719a053bee513d3b60151925eef2#diff-2a4d38cdb52409fe5ff7f6c6b3ae80b79b88e0246ebe5fdb88020d65eea1c3ef

makes the IndexReplicas and IndexShards more similar. 

If you don't mind, could you change the code in bench_gpu_1bn.py, verify it and submit a PR with the modification?

Thanks!
