### ISSUE TITLE
Reexport Faiss version in c_api

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1720]
# Summary

Hello.

Library supports version defines here
https://github.com/facebookresearch/faiss/blob/master/faiss/Index.h#L19

I think this functionality will be useful in *c_api*.

**Comment by Enet4** [comment]
For additional context, this has been brought up at faiss-rs [here](https://github.com/Enet4/faiss-rs/pull/14#discussion_r578368933), as a potential aid at determining whether some feature can be used by the given bindings.

I tried to understand how Python exports the version of Faiss. I suspect that all it does is hard-code the version from the header file via SWIG.
We could also copy those symbol declarations into one of the headers of the C API through some means, but maybe there is interest in embedding the version into the implementation objects instead (.a / .so). This would allow bindings to provide support for a range of versions, although currently this poses some risks due to versions not being semver compliant.

For the time being, it would be an improvement for users of the C API to have access to the same symbol definitions.

**Comment by mdouze** [comment]
Right, we should think about this.

**Comment by ava57r** [comment]
Other version 
https://github.com/facebookresearch/faiss/blob/master/CMakeLists.txt#L10
than
https://github.com/facebookresearch/faiss/blob/master/faiss/Index.h#L19

**Comment by mdouze** [comment]
Right, let's make an API entry to return the version (in the same fashion as get_compile_options() )

**Comment by junjieqi** [comment]
https://github.com/facebookresearch/faiss/pull/3688

now the version is supported from C_API
