### ISSUE TITLE
How to get top k dissimilar vectors

### ISSUE THREAD

**Issue by userg** [facebookresearch/faiss#1733]
# Summary

Is it possible to tune the distance metric or is there some other way to get top K dissimilar results for a query?

Interface: 
- [ ] C++
- [x] Python

**Comment by wickedfoo** [comment]
For METRIC_INNER_PRODUCT for a query vector `x` you can pass in `-x`.

For L2, if and only if your data is on the surface of a unit hypersphere centered at `c`, you can pass in `2c - x` for a query vector `x`.

Otherwise, the only option is brute-force computation and look at all the results and pick the most dissimilar. But the (Gpu)IndexFlat indices are not set up to return the furthest away vectors, so you'd have to inefficiently hack this with range search, or just do the brute-force distance comparison yourself and filter the results.
