### ISSUE TITLE
Find the number of centroids for index_factory

### ISSUE THREAD

**Issue by phuongtrau** [facebookresearch/faiss#1734]
I have a datasheet which shape is 1*512 for each.
What should i choose the number of centroids for clustering (like IVF1024 or IVF16384), if i have at least 1M datas or 10M datas or even 100M datas?
Is choosing this number base on smt?

**Comment by KinglittleQ** [comment]
`sqrt(N * nlists)` would be a good initial choice for the IVF indexes. 

The number of distance calculations in searching is rougly `ncentroids + nlists * (N / ncentroids)`. Let's denote `ncentroids` as `a`, `nlists` as `k` and `(N / ncentroids)` as `b`. We have:
```
#calculations = a + k * b s.t. a * (k * b) = k * N
```
When `a = k * b = sqrt(k * N)`, `a + k * b` would be minimun.


In fact, it is more complicated since it needs a tradeoff between accuracy and speed.

This is my intuition I hope it could help you.

**Comment by mdouze** [comment]
see also 
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index

**Comment by phuongtrau** [comment]
> `sqrt(N * nprobe)` would be a good initial choice for the IVF indexes.
> 
> The number of distance calculations in searching is rougly `ncentroids + nprobe * (N / ncentroids)`. Let's denote `ncentroids` as `a`, `nprobe` as `k` and `(N / ncentroids)` as `b`. We have:
> 
> ```
> #calculations = a + k * b s.t. a * b = N
> ```
> 
> When `a = k * b = sqrt(k * N)`, `a + k * b` would be minimun.
> 
> In fact, it is more complicated since it needs a tradeoff between accuracy and speed.
> 
> This is my intuition I hope it could help you.

Thank you.
