### ISSUE TITLE
Memory allocation assertion on "index.add(x)" on loop

### ISSUE THREAD

**Issue by xolott** [facebookresearch/faiss#175]
Hi,

I'm testing faiss with vectors of 128 values. I create a database with 10M of vectors, then test the `GpuIndexFlatL2` adding the vectors 100K at a time on the first test, and 1M the second test. But, no matter if I set the temp memory to 18% or 1% still give me the same assertion error.

Always, at the same point, around 8.3M of vectors, the script terminate with:
```
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:20; details: Failed to cudaMalloc 8589934592 bytes
```

The loop code is:
```

    res = faiss.StandardGpuResources()
    res.setTempMemoryFraction(0.01)
    flat_config = faiss.GpuIndexFlatConfig()
    flat_config.device = 1
    index = faiss.GpuIndexFlatL2(res, d, flat_config) 
    chunk_loop = int(math.ceil((db_test_size * 1.0 )/ (chunk_size * 1.0)))
    for l in range(chunk_loop):
        print("Chunk: ", l)
        db_data = get_vectors(size=chunk_size, offset=chunk_size * l)
        xb = np.zeros((len(db_data), d), dtype='float32')
        for i, (vec, per) in enumerate(db_data):
            e = np.asarray(vec, "float32")
            np.copyto(xb[i], e)
            per_class_id_list.append(per)
        del db_data 
        index.add(xb)  # add vectors to the index
```
        

I'm continuously watching the GPU memory usage, and at that point, before the assertion, the GPU has 4576/8111 MB allocated. So why faiss is trying to allocate 8G of GPU memory?, when I add 100K vectors at a time. How faiss decide how much memory it had to allocate on every add method call? I thought that this was based on the added vector size, but with 100K or 1M batching it tries to allocate the same amount of memory.

I'm using a GTX 1080 on ubuntu 16.04 with latest faiss

**Comment by wickedfoo** [comment]
GpuIndexFlatL2 sizes data in much the same way as `std::vector<>` or other containers. Namely, by adding a little at a time instead of all at once, each time it doesn't have enough space for what you want to add to it, it will grow the size of its allocation by a factor of 2 and copy the data over, freeing the old allocation after the copy is done. The data it contains needs to be contiguous on the GPU as well.

Thus, you are ok in having 8M vectors in the array, and the container currently has an allocation for 8 * 1024 * 1024 * 128 * sizeof(float) = 4 GiB since 8 * 1024 * 1024 is the next highest power of 2 above 8M, and then when you add the next chunk of 1M, it has to allocate more room, which results in the exactly 8 GiB allocation you are seeing.

The solution here would be to just add all 10M at once from the CPU.
