### ISSUE TITLE
How does IndexIVFFlat cast to FaissIndex?

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1756]
# Summary

Hello.

How do I cast IndexIVFFlat cast to FaissIndex?

IndexIVF supports this cast, but I can't create it from c_api
https://github.com/facebookresearch/faiss/blob/master/c_api/IndexIVF_c.h#L39.

IndexIVFFlat does not contain this feature https://github.com/facebookresearch/faiss/blob/master/c_api/IndexIVFFlat_c.h#L26.

Thanks.

Running on:
CPU

Interface: 

c_api

**Comment by Enet4** [comment]
Oh, this was probably just an overlook. Other index types are aliased into the same opaque type for convenience, but one can still cast the pointer of one index type to another manually. In C, this is with the C style cast `(FaissIndex*)`. In Rust, `as *mut FaissIndex`.

I suppose a pull request to tweak the declaration of `FaissIndexIVFFlat` would be welcome too.

**Comment by ava57r** [comment]
Why does not c_api IndexIVF support functions
`faiss_IndexIVF_new`,
`faiss_IndexIVF_new_with`,
`faiss_IndexIVF_new_with_metric`?

**Comment by Enet4** [comment]
The C API is not exhaustive. I tried to cover all much of the native API as to be usable, but some functions may have been left out. In time, Faiss may introduce new features, which would also need to be translated into the C API for them to be accessible.

I probably did not add those functions because one can already create an IVF index via the index factory function. But a PR providing an accurate translation of these constructs for the C API would also be welcome.

**Comment by Enet4** [comment]
This should be good to close, now that #1764 was merged.
