### ISSUE TITLE
Differences in GPU search time using shards

### ISSUE THREAD

**Issue by viniciussn** [facebookresearch/faiss#1776]
# Summary
Hi guys!
I have a scenario where I need to split an IVFPQ index into two shards.
The shards are also IVFPQ indexes, but they will only have half the vectors of the original index (approximately). 
I tested two strategies to split the index:

Strategy 1 - The vectors are distributed between the two shards in a round-robin fashion. Thus, each shard will have data in all inverted file entries.

Strategy 2 - The inverted file entries are distributed between the two shards in a round-robin fashion. Each shard will only have data in half of the inverted file entries (the remaining will be empty). So, each inverted file entry in a shard (if not empty) has all the vectors of that entry.

So, the idea is to perform a search in each shard and merge the results later.
When I perform the search in these two shards using CPU, the total search time (shard 1 + shard 2) is the same for both strategies.
The problem is, when I perform the search in these two shards using GPU, the search is a little faster (~3%) in the shards created with Strategy 1.

I performed an experiment that consists of searching 10k queries. The original index has 200 millions SIFT vectors. Each shard has approximately 100 millions vectors. The average search time for 5 runs of this experiment on the GPU was:
Strategy 1: 2.028 seconds
Strategy 2: 2.095 seconds

I ran the experiments again, now using 32 shards and the average search time was:
Strategy 1: 22.704 seconds
Strategy 2: 23.364 seconds

I know that the time difference is very small, but I can’t figure out why this happens. Do you guys have any clue?
Part of the source code used is available below.
# Platform

OS: Ubuntu 20.04.1 LTS

Faiss version: 31393764cccb3ae94e8a604e1fd891b331c46221

Installed from: compiled by myself 

Faiss compilation options: only the default options (./configure && make) 

Running on:
- [ ] CPU
- [X] GPU - NVIDIA GTX 1070 - CUDA 10.2

Interface: 
- [X] C++
- [ ] Python

# Reproduction instructions

```
#include <bits/stdc++.h>
#include <sys/time.h>

#include "data.h"
#include "faiss/Index.h"
#include "faiss/IndexFlat.h"
#include "faiss/IndexIVFPQ.h"
#include "faiss/clone_index.h"
#include "faiss/gpu/GpuCloner.h"
#include "faiss/gpu/GpuClonerOptions.h"
#include "faiss/gpu/GpuIndexIVFPQ.h"
#include "faiss/gpu/StandardGpuResources.h"

#define NSHARDS 16

int dim = 128;
int n_coarse_centroids = 4096;
int m = 8;
int n_bits = 8;
int w = 16;
int k = 100;
int n_queries = 10000;

std::string populated_index_file_name = "populated_1bi_200m.index";
std::string query_file_name = "sift1b_query.bvecs";


double now()
{
    struct timeval tv;
    gettimeofday(&tv, nullptr);
    return tv.tv_sec + tv.tv_usec * 1e-6;
}

void strategy1(faiss::IndexIVFPQ* cpu_index, std::vector<faiss::IndexIVFPQ*>& cpu_shards)
{
    cpu_index->own_fields = false;
    faiss::InvertedLists* invlists = cpu_index->invlists;
    cpu_index->invlists = new faiss::ArrayInvertedLists(invlists->nlist, invlists->code_size);

    for (int i = 0; i < NSHARDS; i++) {
        cpu_shards[i] = dynamic_cast<faiss::IndexIVFPQ*>(faiss::clone_index(cpu_index));
        cpu_shards[i]->ntotal = 0;
    }

    int shard_counter = 0;
    for (int i = 0; i < invlists->nlist; i++) {
        for (int j = 0; j < invlists->list_size(i); j++) {
            const uint8_t* code = invlists->get_single_code(i, j);
            const faiss::Index::idx_t id = invlists->get_single_id(i, j);
            cpu_shards[shard_counter % NSHARDS]->invlists->add_entry(i, id, code);
            cpu_shards[shard_counter % NSHARDS]->ntotal++;
            shard_counter++;
        }
    }
    delete invlists;
}

void strategy2(faiss::IndexIVFPQ* cpu_index, std::vector<faiss::IndexIVFPQ*>& cpu_shards)
{
    cpu_index->own_fields = false;
    faiss::InvertedLists* invlists = cpu_index->invlists;
    cpu_index->invlists = new faiss::ArrayInvertedLists(invlists->nlist, invlists->code_size);

    for (int i = 0; i < NSHARDS; i++) {
        cpu_shards[i] = dynamic_cast<faiss::IndexIVFPQ*>(faiss::clone_index(cpu_index));
        cpu_shards[i]->ntotal = 0;
    }

    for (int i = 0; i < invlists->nlist; i++) {
        cpu_shards[i % NSHARDS]->invlists->add_entries(i, invlists->list_size(i), invlists->get_ids(i), invlists->get_costrategy1(i));
        cpu_shards[i % NSHARDS]->ntotal += invlists->list_size(i);
    }   
    delete invlists;
}

int main()
{
    std::vector<faiss::IndexIVFPQ*> cpu_shards(NSHARDS);
    Data query_dataset(query_file_name.data(), dim);
    faiss::gpu::StandardGpuResources res;
   
    // Reading index
    faiss::IndexIVFPQ* cpu_index = dynamic_cast<faiss::IndexIVFPQ*>(faiss::read_index(populated_index_file_name.c_str()));
    cpu_index->nprobe = w;

   // Creating shards
    strategy1(cpu_index, cpu_shards);
    // strategy2(cpu_index, cpu_shards);

    // Reading queries
    float *query_vecs = query_dataset.getNextBatch(n_queries);

    float *distances = new float[n_queries * k];
    faiss::Index::idx_t* labels = new faiss::Index::idx_t[n_queries * k];

    double start, end, search_time = 0, transfer_time = 0;
    for (int s = 0; s < NSHARDS; s++) {
        start = now();
        faiss::gpu::GpuIndexIVFPQ* gpu_index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(faiss::gpu::index_cpu_to_gpu(&res, 0, cpu_shards[s], nullptr));
        transfer_time += now() - start;

        start = now();
        gpu_index->search(n_queries, query_vecs, k, distances, labels);
        end = now();
        search_time += end - start;
    }

    std::cout << "Search took " << search_time << " s.\n";
    std::cout << "Transfer took " << transfer_time << " s.\n";
    std::cout << "Throughput " << n_queries / (search_time + transfer_time) << " s.\n";
}

```

**Comment by wickedfoo** [comment]
What is the rationale for sharding in your use case?

Sharding typically only makes sense on the GPU if you have each shard on a separate GPU, and if you are using a different CPU thread to drive each GPU. The IndexShards class does this naturally for you.

Otherwise, calling different shards from the same CPU thread (whether on the same or different GPUs) may not give you any concurrency. It is even more problematic if the input/output data to the GPU index calls is CPU memory not GPU memory, in which case all index calls are fully sequential if you call them in the same CPU thread, even if the indices are on different GPUs, as there is a cudaMemcpy that is synchronous at the beginning and end of each call.

**Comment by viniciussn** [comment]
Hi @wickedfoo,

I’m working in an online scenario where my database doesn’t fully fit in GPU memory (only fit in CPU memory).
So, I create N shards, where each shard has a maximum size equal to the GPU memory, and I keep one query queue for each shard.
During the search phase, each shard is copied to the GPU, one at a time, and performs the search of all queries in its queue. Later the partial results are merged in a global one.
For Strategy 1, all arriving queries need to go into all queues.
For Strategy 2, a query only needs to go into a queue of a shard that has an inverted file entry that this query needs to scan.
Thus, I am testing different strategies to create shards and I end up in this problem.

**Comment by wickedfoo** [comment]
Copying an index to the GPU to perform a search there is likely slower than just doing it on the CPU, unless you are exhaustively searching the index many times while it is on the GPU.

Instead of copying them successively yourself, you can also try using CUDA unified memory. This will allow you to have an index on the GPU that can be as large as the combined GPU + CPU memory, though internally it will still have the cost of a copy if the data is not resident currently on the GPU you need it on, though this will be fully transparent for you. It is also likely that the entire index is not needed in most cases.

To do this, in the GpuIndex config object, set `memorySpace` to `MemorySpace::Unified` (there is a Python equivalent, perhaps `faiss.Unified` or `faiss.MemorySpace.Unified` or some such too. Then you can create a single large index on the GPU even if it exceeds a single GPU's memory.

https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/GpuIndex.h#L25
