### ISSUE TITLE
Inconsistent result in IndexIVFFlat/GpuIndexIVFFlat

### ISSUE THREAD

**Issue by Hari-Sheng** [facebookresearch/faiss#178]
Hi there,
This might be a dummy question, but in our experiment we have found significant inconsistence in the CPU/GPU implementation of `IndexIVFFlat` --- the Gpu version is way off. 
We wonder do we missed something in setup, or the implementation is different and that is expected. Thank you so much!

I have attached my test case below:
```python
class TestFAISSBaseCase(unittest.TestCase):
    def setUp(self):
        self.d = 128
        self.nb = 100000
        self.nq = 70000      
        self.nlist = 16 
        self.gpu = True
        self.k = 1000
        self.N_retrain = 1000
        self.seed = 123
        self.nprobe = 16
        self.threshold = 0.95
        self.scale = 1
        self.random = np.random.normal
    
    def test_accuracys(self):
        d, nb, nq = self.d, self.nb, self.nq
        k = self.k
        nlist, gpu, nprobe = self.nlist, self.gpu, self.nprobe
        threshold = self.threshold
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)
        
        res = faiss.StandardGpuResources()
        index_gpu = faiss.GpuIndexIVFFlat(
            res,
            d,
            nlist,
            faiss.METRIC_INNER_PRODUCT)
         
        quantizer = faiss.IndexFlatL2(d)
        index_cpu = faiss.IndexIVFFlat(
                    quantizer,
                    d,
                    nlist,
                    faiss.METRIC_INNER_PRODUCT)
        index_cpu.nprobe = self.nprobe
        index_gpu.nprobe = self.nprobe
        
        xb = np.random.random(size=(nb, d)).astype('float32')*self.scale
        xq = self.random(size=(nq, d)).astype('float32')*self.scale
        test_ind = np.random.randint(0,nq,k)
        
        index_cpu.reset()    
        index_cpu.train(xb)
        index_cpu.add(xb)
        D_cpu, I_cpu = index_cpu.search(xq[test_ind], 1)
        count = 0 
        for _ in range(self.N_retrain):
            index_gpu.reset()    
            index_gpu.train(xb)
            index_gpu.add(xb)
            D_gpu, I_gpu = index_gpu.search(xq[test_ind], 1)
            count = max(count, np.sum(I_cpu[:,0]==I_gpu[:,0]))
        
        print('In {} trial, correctly retriving {} indices'.format(k, count))
        accuracy = count*1.0/k
    
        print('Retriving accuracy {}%'.format(accuracy*100))
        self.assertTrue(accuracy > threshold)
```

```
In 1000 trial, correctly retriving 176 indices
Retriving accuracy 17.6%
F
```

**Comment by wickedfoo** [comment]
Way off meaning what exactly?

There is no guarantee that the distance results will be exactly the same due to difference in floating point reduction order (i.e., floating point addition is not associative). It appears that you are counting whether indices reported are ordered exactly the same, which is not guaranteed.

What one needs to look at is how far apart they are reported in the list (e.g., something like, in the CPU list, a result has index 392 and in the GPU a result has index 396, a difference of +4 which is reasonable, compared to tens or more, which is not), and what the fraction of overlap between the two reported sets are. This is what the GPU tests do.

**Comment by Hari-Sheng** [comment]
Sorry I did not get what you said about `how far apart they are reported in the list`. Here I only request top-1 nearest neighbor, hence if the index order does not match indicates the result is different. 
I have another test that compare the returns to exact result which also fails on GPU. Could you point me to the GPU tests?

**Comment by wickedfoo** [comment]
The top-1 as reported on the GPU or the CPU may be not be in first place on the other, but could be in, say, the 3rd or 5th or whatever place. You would have to compare k = 1 on one index with k = 10 or 20 on the other, and see how far apart the reported distances are.

If by "exact result" you mean IndexFlat / GpuIndexFlat, note that the same issue is present. The distances will always be within some epsilon that is due to the different order of floating point operations. Both GPU and CPU are performing the same math, but in different order. Also note that different BLAS libraries on the CPU may return different values.

**Comment by Hari-Sheng** [comment]
If I understand it correctly, you are saying that because the distance of top-k neighbors are so close to each other, in floating number calculation we can not tell which one come first? That makes sense. So I should take the top-K neighbors as set and compare the overlapping of the set? Could you let me know how did you guys test it out/guarantee the accuracy? I mean by overlapping or distance (with in a bound)?

**Comment by mdouze** [comment]
Hi 

`index_gpu.nprobe = self.nprobe` does not set the nb of probes for the GPU, this is done via  `index_gpu.setNumProbes(self.nprobe)`. This codes most likely uses the default nprobe, which is 1.

**Comment by mdouze** [comment]
Assuming this is fixed.
