### ISSUE TITLE
Faiss gpu does not support product-quantizers with 256 reproduction values

### ISSUE THREAD

**Issue by YJYJLee** [facebookresearch/faiss#1800]
# Summary
I found out that faiss-gpu only supports sub-quantizers with 256 reproduction values, which means ProductQuantizer.nbits=8.
Also I found out that faiss-cpu supports any nbits including 8.
Is there any reason why faiss-gpu only supports 8bits for product quantization?

I found about this ./faiss/gpu/GpuIndexIVFPQ.cu:82
`  FAISS_THROW_IF_NOT_MSG(ivfpqConfig_.interleavedLayout || index->pq.nbits == 8,
                         "GPU: only pq.I  == 8 is supported");`

**Comment by mdouze** [comment]
Support for a wider range of bit widths on GPU is work in progress.

**Comment by wickedfoo** [comment]
This was an implementation limitation. A smaller number of reproduction values per subspace can easily be supported, but what we also want is bit packing so that a 4 bit encoding also only takes 4 bits per sub-Q, instead of each one still taking a byte.

A diff has been in progress on my end but has been delayed due to non-Faiss work this half, but should be coming in the next few months.

**Comment by YJYJLee** [comment]
Well understood , thanks for the reply :)
