### ISSUE TITLE
How to improve  accuracy

### ISSUE THREAD

**Issue by deitycitian** [facebookresearch/faiss#184]
Hello,
I read this from Wiki:
"Overall, if memory is not a concern (and 8 GPUs can fit 100M vectors easily), the IVFFlat is both faster and more accurate."
 
So, is IVFFlat the most accurate method ?  And with this,  Are there some parameters can be set to improve the accuracy ?  

Any suggestion to improve the accuracy will be appreciated. Thank you all.

**Comment by wickedfoo** [comment]
IndexFlat / GpuIndexFlat is the most accurate as it is the brute-force distance computation between all pairs of vectors.

Every other index involves some approximation.

IVFFlat is more accurate than IVFPQ because it doesn't encode the vectors (it keeps around the raw floating-point data) but it is a non-exhaustive search.

IVFPQ is less accurate but requires much less storage, as it encodes the vectors to a user-specified number of bytes.

Increasing accuracy with both IVFFlat and IVFPQ requires increasing nprobe, or decreasing nlist. This requires more time for the query. IVFPQ also has separate encoding options which affect the speed/accuracy/storage tradeoffs.

Read papers on product quantization or inverted file indexing for more information.

**Comment by deitycitian** [comment]
Thank you
