### ISSUE TITLE
Best way to use Faiss for binary feature vectors, that need mapping to specific ids?

### ISSUE THREAD

**Issue by PaperLuigiMario** [facebookresearch/faiss#1855]
# Summary
Hi there,
I am looking into this library because we have a huge dataset (>50 bil, growing daily) that is made up of features that are just binary vectors like [0,1,0,...]. Each vector has an associated non-sequential unique id. Memory is a concern for us, and we'd need it to be quite fast. Approximate search is ok in our case.
I see there are binary indexes, but it doesn't seem these support the "add_with_ids" function we'd need. Additionally, I see I can use the Flat index but in order to "add_with_ids" I have to convert my features into float32s, which defeats the purpose of saving on memory.

Can someone please help recommend the right index for us? Thank you so much in advance!

Faiss version: faiss-cpu 1.7.0

Installed from: pypi, faiss-cpu 1.7.0

Faiss compilation options: default

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

Ideally trying to do something like this:

import numpy as np
import faiss
d = 64                         # dimension
nb = 100000000000                # database size
db= np.random.randint(2, size=(nb, d)).astype('uint8')
print(db[:3])

print('db n', db.shape[0], 'db d', db.shape[1])

idds= np.arange(0, db.shape[0], dtype="int64") 
print(idds.shape[0])

k = 1

INDEX_KEY= "IDMap, BFlat" <--- this isn't supported
index = faiss.index_binary_factory(d, INDEX_KEY) <--- this isn't supported

index.add_with_ids(db,idds) <--- this isn't supported

D,I=index2.search(db[:5], k)
faiss.write_index(index, filename)
print(I)
print(D)

**Comment by PaperLuigiMario** [comment]
Thank you so much-- my understanding with that one is it already has the add_with_ids function?

**Comment by PaperLuigiMario** [comment]
Thanks for your suggestion, but I still seem to be having some issues translating into IndexBinaryIVF. When I try adapting to the IndexBinaryIVF with this:

import numpy as np
import faiss
d = 64                         # dimension
nb = 100000                  # database size
db= np.random.randint(2, size=(nb, d)).astype('float32')
print(db[:3])

print('db n', db.shape[0], 'db d', db.shape[1])
#returns db n: 100000 db d: 64

idds= np.arange(0, db.shape[0], dtype="int64")#.astype('int64') 
print(idds.shape[0])
#returns 100000

k = 1
#INDEX_KEY = "IDMap,Flat"
INDEX_KEY="BIVF1024"
#index = faiss.index_factory(d, INDEX_KEY)
index=faiss.index_binary_factory(d, INDEX_KEY)
index.nprobe = 4


# Adding the database vectors.
index.add_with_ids(db,idds)


D,I=index.search(db[:5], k)
faiss.write_index(index, filename)
print(I)
print(D)
print('got to the end')

I get an Assertion Error on the add_with_ids line:
def replacement_add_with_ids(self, x, ids):
    271         n, d = x.shape
--> 272         assert d * 8 == self.d

This code ran fine for the flat index and the shape of all the vectors being used seem to be as expected...? Can you help me understand how to fix this please?

**Comment by PaperLuigiMario** [comment]
Hey, I was able to work this out -- I am wondering is there any way to compress this index further? I see it comes out to (using our data) about 4.5 GB which is our upper limit. What else would you recommend for this then?

**Comment by QwertyJack** [comment]
> Hey, I was able to work this out -- I am wondering is there any way to compress this index further? I see it comes out to (using our data) about 4.5 GB which is our upper limit. What else would you recommend for this then?

100 billion binary vectors of `dim=64` take up to 800GB. Apparently, index of binary vectors cannot be compressed, but it's a better idea to serve your index via a cluster instead of a single node.

Ref:

- [How can I distribute index building on several machines?](https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-distribute-index-building-on-several-machines)
- [IndexShards: combining results from several indexes](https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#indexshards-combining-results-from-several-indexes)
- [Indexes that do not fit in RAM](https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM)

**Comment by mdouze** [comment]
There is no compression scheme for binary vectors in Faiss (because we assume that if they are in binary, they were compressed before). So the bottom line is that you will use at least as much memory as the size of the input data. 

About your example above, it's not very clear what the data dimension is. If d is the number of bits, then the size of the uint8 data matrix should be (d // 8) because each byte can hold 8 bits.
