### ISSUE TITLE
Adding python interface for NSG

### ISSUE THREAD

**Issue by hkzhang91** [facebookresearch/faiss#1896]
Do you have a plan to add python interface for NSG algorithm？

**Comment by KinglittleQ** [comment]
It is already supported at the `master` branch. You could either call `faiss.IndexNSGFlat(d, R)` or `faiss.index_factory(d, f"NSG{R}")` to construct an IndexNSG object.

**Comment by hkzhang91** [comment]
> It is already supported at the `master` branch. You could either call `faiss.IndexNSGFlat(d, R)` or `faiss.index_factory(d, f"NSG{R}")` to construct an IndexNSG object.

Thanks for your reply.  I have an another question about NSG implemented in here. According to the paper "Fast Approximate Nearest Neighbor Search With The Navigating Spreading-out Graph", init KNN graph used in NSG is build via EFANNA algorithm. While, in your code, it seems that the init KNN graph is build via NN-descent algorithm.  Will this make a difference in search accuracy?

EFANNA shows better performance than NN-descent[1], which means that the init KNN graph build by EFANNA is better than that of NN-descent and it may leads to a higher search accuracy.  Have I understood correctly?

[1] Fu, Cong, and Deng Cai. "Efanna: An extremely fast approximate nearest neighbor search algorithm based on knn graph." arXiv preprint arXiv:1609.07228 (2016).

**Comment by KinglittleQ** [comment]
Efanna is an algorithm based on NN-Descent and it implemented NN-Descent in the official open-source code. Only the NN-Descent part is used to build a KNN graph in the paper you mentioned. So this implementation is the same as the original official code.

Furthermore, we provide an `index.build()` method to allow users to build an NSG graph given a prebuilt KNN graph. You could build an exact KNN graph rather than an approximate KNN graph by brute force searching using GPU and then call `index.build(x, knn_graph)` to build an NSG.

**Comment by hkzhang91** [comment]
> Efanna is an algorithm based on NN-Descent and it implemented NN-Descent in the official open-source code. Only the NN-Descent part is used to build a KNN graph in the paper you mentioned. So this implementation is the same as the original official code.
> 
> Furthermore, we provide an `index.build()` method to allow users to build an NSG graph given a prebuilt KNN graph. You could build an exact KNN graph rather than an approximate KNN graph by brute force searching using GPU and then call `index.build(x, knn_graph)` to build an NSG.

Your replies have solved all my problem. Thanks a lot.
