### ISSUE TITLE
why index.add is too slow when added-number beyond 100M

### ISSUE THREAD

**Issue by deitycitian** [facebookresearch/faiss#195]
Hello,
I found that the index.add is too slow when added-number beyond 100M(1 billion) with 2% cpu usage.  Some information,  nt : 100M， nq : 200M, probe: 204800

**Comment by wickedfoo** [comment]
which index?

**Comment by deitycitian** [comment]
indexFlat.

**Comment by wickedfoo** [comment]
IndexFlat / GpuIndexFlat must make sure that enough memory is allocated, and if not, it will allocate a new region of memory and copy over the old data and then append to it. The larger the add size (and the existing database), the larger this will get.

Unlike the other indices, IndexFlat has a larger penalty for incremental adds.

Are you adding incrementally or all at once?

**Comment by wickedfoo** [comment]
For instance, if you are adding 100 million 128-d vectors, this requires an additional 51.2 GB of memory for the index. If this exceeds your physical RAM, you will potentially be swapping the page file or the memory allocation will outright fail.

**Comment by deitycitian** [comment]
Thanks for your reply.   I add  100  thousand vectors a time incrementally,  until 2 billion . My RAM is 128G. Is it enough ? What to do with this ? Increase the add number a time ?

**Comment by wickedfoo** [comment]
For IndexFlat / GpuIndexFlat, you should add them all at once if possible.
How big are your vectors? The size they will take in memory is at least #
of dimensions * 4 bytes each with IndexFlat, so you will run out of memory
likely before 16-dimension vectors.

IndexFlat / GpuIndexFlat does not compress vectors, and is an exact,
brute-force search. It is likely not what you want?

**Comment by deitycitian** [comment]
The size of My vectors is 102.4G. And It is not possible to add at once. So, is it not way to fix this ?

Yes, IndexFlat is what I want. I would rather accracy than speed.

**Comment by wickedfoo** [comment]
You are likely running out of memory then. The overhead of storing 102.4 GB of vectors is larger than 102.4 GB most likely, plus the requirements of the rest of your system. In this case, you can come closer by adding them incrementally instead of all at once (so you don't need 2 x 102.4 GB of memory), but the allocation for storing the vectors needs to grow as well, which is probably being done by the `std::vector` growing heuristics. I believe adding all at once exactly sizes the data.

You'd have to consider a compressed index to tradeoff less memory for less accuracy, or split your index into two shards on two separate machines, or buy more memory.

Alternatively, if your source data is from a file on disk, you can memory map that file instead, and add from that all at once; the memory map will not require 102.4 GB of physical memory, only virtual memory.

**Comment by deitycitian** [comment]
Thanks very much.
