### ISSUE TITLE
GpuIndexIVFFlat add_c() train_c() can't take CUDA pointer from PyTorch

### ISSUE THREAD

**Issue by windweller** [facebookresearch/faiss#206]
Following the PyTorch example:  https://github.com/facebookresearch/faiss/blob/master/gpu/test/test_pytorch_faiss.py
I wanted to be able to directly give PyTorch CUDA Tensor pointer to train_c() and add_c()

However, I get a segmentation fault. To reproduce the bug, can use the following REPL line:

```python
>>> import faiss; import torch
>>> d = 128; nq=5; nb=1000
>>> xb = faiss.rand(nb * d).reshape(nb, d) * 10
>>> xb_t = torch.FloatTensor(xb).cuda()
>>> xb_t.storage().data_ptr()
77398409216
>>> casted = faiss.cast_integer_to_float_ptr(xb_t.storage().data_ptr())
>>> casted
<Swig Object of type 'faiss::HeapArray< faiss::CMax< float,long > >::T *' at 0x7f484b091d80>
>>> res = faiss.StandardGpuResources()
>>> index = faiss.GpuIndexIVFFlat(res, d, 5, faiss.METRIC_INNER_PRODUCT)
>>> index.setNumProbes(12)
>>> index.train_c(nb, casted)
Segmentation fault (core dumped)
```

If xb is not on cuda(), segmentation fault would not happen.
so if in addition, we add a line saying `xb_t = xb_t.cpu()`, then this all works very well.

**Comment by mdouze** [comment]
Hi, 
Yes I understand why this happens: the averaging of points assigned to a centroid is still done on CPU. 
It is unlikely that we change this, because: 
- it adds a lot of flexibility. In particular the training data does not need to fit in GPU mem.
- the cost of the assignment stage is dominant, and the data for that stage is read from pinned memory in parallel with computations, so it is efficient
- the cost of copying the training data to `xb_t = xb_t.cpu()` is negligible compared to assignment

However, adding elements with `add_c` should work.

@wickedfoo, any additional comment?

**Comment by wickedfoo** [comment]
Weird I thought you should be able to call train() on the GpuIndexIVFFlat (or GpuIndexIVFPQ) with GPU-resident data, but looking at the code it appears not? I guess that was never tested or implemented.

train() will still leverage the GPU though for the distance calculation though.

add() and search() can definitely take GPU-resident data though, that does work.

**Comment by mdouze** [comment]
Closing issue.
