### ISSUE TITLE
InvertedListScanner in Python

### ISSUE THREAD

**Issue by pletessier** [facebookresearch/faiss#2072]
# Summary
I would like to try using InvertedListScanner in Python, but as stated in the doc, it's not available. Would it be possible to change that ? 

I tried to build after commenting lines in swigfaiss.swig : 
```
//%ignore InvertedListScanner;
//%ignore BinaryInvertedListScanner;
```

I can now call the function `scanner.set_query()` in Python, but I get this error : 
`TypeError: in method 'InvertedListScanner_set_query', argument 2 of type 'float const *'`

**Comment by mdouze** [comment]
That is a good question... 
The main problem is that the InvertedListScanner object is intended to be fast, so calling it from slow python defeats the purpose in many use cases.

The error reported above is just because you need to convert the ndarray object to a C++ float* with faiss.swig_ptr(), see https://github.com/facebookresearch/faiss/wiki/Faiss-code-structure#handling-of-c-pointers

**Comment by mdouze** [comment]
Yes please do.
