### ISSUE TITLE
I met a problem when I compiled tests/test_blas.cpp on ubuntu

### ISSUE THREAD

**Issue by lzy921221** [facebookresearch/faiss#21]
I am a student and recently I am interested in image retrieval. When I downloaded the code and started to compile it, I have some trouble. I have already install Clapack, but it still have some errors. 
If I use "make tests/test_blas" , I got the message below.
![image](https://cloud.githubusercontent.com/assets/23226251/23637839/e0a5389c-0318-11e7-9a7b-99b799b74fe9.png)
If I use "g++ tests/test_blas.cpp", I got another message below.
![image](https://cloud.githubusercontent.com/assets/23226251/23637856/05f9abb4-0319-11e7-93ed-5b421e881f27.png)
It really confused me. I wonder if you can help me to solve this trouble.

**Comment by shuiko1** [comment]
Yes. I got this problem too!  I search the Web: it's may be caused by the lapack library. So i download the source and compile install. But problem not solved. I also use apt-get install those library. It reminds me those libraries already installed. 
So i have no idea what it's happened. May someone can help us. Thank you.

**Comment by thbqlf** [comment]
I got this problem too!

**Comment by mdouze** [comment]
Hi 

You have several problems with your command line: 

- you are using a C compiler (cc) to compile C++, which is why you see errors about `new`

- you did not set the BLAS linking flags. 

Please copy an example makefile.inc and edit the flags as indicated in the INSTALL file.
