### ISSUE TITLE
Python sharded GPU index

### ISSUE THREAD

**Issue by bkj** [facebookresearch/faiss#216]
Hi --

I'm wondering how to create a GPU index using `IndexShards` as alluded to in the wiki.  I understand how to create an index that's copied across GPUs using `IndexProxy`:

```
dim = 128
ngpu = faiss.get_num_gpus()

res = [faiss.StandardGpuResources() for i in range(ngpu)]

flat_config = []
for i in range(ngpu):
    cfg = faiss.GpuIndexFlatConfig()
    cfg.useFloat16 = True
    cfg.device = i
    flat_config.append(cfg)

indexes = [faiss.GpuIndexFlatL2(res[i], dim, flat_config[i]) for i in range(ngpu)]
findex = faiss.IndexProxy()
for sub_index in indexes:
    findex.addIndex(sub_index)
```

Is there an analogous example of using `IndexShards`?  In the benchmark code, it looks like there are some examples of copying an index from the CPU to multiple GPU shards, but ideally I'd like to construct the sharded index directly.

Thanks

**Comment by mdouze** [comment]
Hi, 
Have you tried just doing: 
```
findex = faiss.IndexShards(d, True, False)
# second False = necessary if you use `add` to individual shards
for sub_index in indexes:
    findex.addIndex(sub_index)
```
Then you can:
- use `add_with_ids` to add elements to`findex` or
- use `add` or `add_with_ids` to add elements to individual shards -> can be done in parallel.

**Comment by hungvanto** [comment]
Hi mdouze,
Can you help me with the problem I'm facing please.
I did as you said in the message above, but after I create findex, I tried to use add_with_ids to add elements to findex but failed.

The error is at follow:
RuntimeError: Error in virtual void faiss::gpu::GpuIndexFlat::addImpl_(int, const float*, const idx_t*) at gpu/GpuIndexFlat.cu:185: Error: '!ids' failed: add_with_ids not supported
It should be because GPU don't support add_with_ids right? So in this case, we can't use IndexShards right? Because the IndexShards is for GPU and require add_with_ids function (which doesn't support GPU).

Please help me correct if there is something wrong.
Thank you so much.

**Comment by mdouze** [comment]
The problem here is that you use a Flat index. They don't support `add_with_ids`. 
To do `add_with_ids`, you should use an `IDMap` instead, as explained here:
https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#faiss-id-mapping

**Comment by hungvanto** [comment]
Hi mdouze,

I can use it now. Thank you for your support. Have a good day ahead.

**Comment by hungvanto** [comment]
Dear Matthijs Douze,

I'm trying to use FAISS for Multi GPUs. Currently, I have 3 Tesla V100
(each with 16GB of DDR5) for storing 2 indexes.
The problem is not with the search time, but with the scalability of the
indexes.
With 1.4 Million vectors storing in Index1, and 1.1 Million vectors storing
in Index2, I use the `index_cpu_to_all_gpus` for both the index, so that
both of them sharing 3 GPUs.
So I want to ask that, currently the GPU DDR5 occupied by 2 indexes is
quite high (9.2GB for GPU1, 8.8GB for GPU2, 8.8GB for GPU3), is there any
thing I can do to lower the DDR5 usage so that I can have my indexes
support more vectors? Or am I using the FAISS wrongly?
My vectors are of 512 dimensions.
Can you please help me to solve this problem? Thank you so much.

Hope you help a good day.

**Comment by mdouze** [comment]
Please refer to https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#using-multiple-gpus for multi-gpu mem usage.

**Comment by hungvanto** [comment]
Dear mdouze,

I think I find what I'm looking for. Thank you so much for your support.
Have a good day ahead.
