### ISSUE TITLE
Question/Feature Request: Nearest Neighbors of Groups of Points

### ISSUE THREAD

**Issue by theahura** [facebookresearch/faiss#2174]
Certain clustering algorithms such as [Hierarchical Affinity Clustering](https://proceedings.neurips.cc/paper/2017/file/2e1b24a664f5e9c18f407b2f9c73e821-Paper.pdf) depend on being able to find a set of nearest neighbors from a group of points. For example, if I have points arranged in a line like:

A -- B ----- C -- D

I could first use FAISS to find nearest neighbors for each point, resulting in groupings

AB ----- CD

I might then want to use FAISS to find the next nearest neighbor to the grouping AB (which is still composed of two separate points, A and B, under the hood), which would return CD.

Does FAISS support this kind of behavior? 

Thanks in advance!

**Comment by mdouze** [comment]
I don't think Faiss indexes are a good fit for this use case, because they usually assume there is a large number of searches to perform to amortize the indexing cost. You may be interested in the raw exact KNN functions 
https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index
