### ISSUE TITLE
Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at /project/faiss/faiss/gpu/utils/StackDeviceMemory.cpp:144

### ISSUE THREAD

**Issue by ashutoshsingh25** [facebookresearch/faiss#2175]
Getting the following error while parallel calling of faiss GPU indexes:

**Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at /project/faiss/faiss/gpu/utils/StackDeviceMemory.cpp:144**

# Platform

OS:  Ubuntu

Faiss version: 1.7.1 

Installed from: faiss-gpu

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by wickedfoo** [comment]
> error while parallel calling

Please read https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

The error is arising because you are likely sharing a single GpuResources object among multiple threads executing concurrently.

You need either mutual exclusion so only one thread operates on a single GpuResources object at one time, or a different GpuResources object dedicated to each thread.

**Comment by ashutoshsingh25** [comment]
Thanks, The issue has been resolved using mutual exclusion.

**Comment by longliu-ll** [comment]
> Thanks, The issue has been resolved using mutual exclusion.

Can you provide a specific solution?
