### ISSUE TITLE
faiss_get_last_error or other error reveal through Python API?

### ISSUE THREAD

**Issue by kden** [facebookresearch/faiss#2243]
# Summary

I want to rule out any failed adds happening with the `add_with_ids` call, but the Python versions of this call generally return `None`.  I see in the faiss project source code there is a `faiss_get_last_error` call in c_api/error_impl.cpp you can make to get the last error.   Is there a way to call this from Python?  I searched the online C++ API documentation at https://faiss.ai/ for `faiss_get_last_error`and didn't come up with anything.

# Platform

OS: 

Faiss version: 

Installed from: conda
`conda list` info for the python library is:
`faiss-cpu                 1.6.3            py37h04f5b5a_0    pytorch
`
Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

No reproduction instructions yet; I want to know how I can call this function from Python.

**Comment by Enet4** [comment]
That function exists exclusively in the C API, since it provides a way to obtain the full error message of the exception last thrown on that thread (C does not have exceptions). The Python bindings consume the native API directly via swig.

Are you sure that failures do not already translate C++ exceptions to python errors? In what operation(s) are you expecting an error to happen?

**Comment by kden** [comment]
I'm not expecting an error so much as trying to track down why I have less index vectors than I expected in the index.  I am adding them in an asynchronous thread with `add_with_ids`, and it only starts to happen when I insert tens of thousands of vectors.  It's entirely possible the problem is with my code, I'm just trying to rule out potential causes.  `add_with_ids` doesn't appear to be throwing any exceptions, so I will look for other things to rule out.
