### ISSUE TITLE
how to calculate the memory usage mannually?

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#229]
Hi, guys: 
https://code.facebook.com/posts/1373769912645926/faiss-a-library-for-efficient-similarity-search/

in the above site, the 'Choosing the index' part, said under the 30GB memory limitation, usingOPQ20_80, IM12X14, PQ20, get a memory below 30GB. I wonder how to get the 30GB memory usage with the given parameters? 

and question 2, in my case, I use the IVFADC in my test, with IVF256, PQ48, dataset size 10 million with dimension 128, how to calculate the memory usage? nbits =8.

**Comment by mdouze** [comment]
Hi 

The memory usage for OPQ20_80,IMI2X14,PQ20 for 1B vectors breaks down as:

- (20+8) * 10^9 bytes for the vectors (codes + ids)
- 2^(2 * 14) * 16 bytes at least for the inverted lists + geometrical allocation overhead 

So it is in fact bigger than 30G....

For IVF256,PQ48 and 10M elements, it will use 480M, with little overhead because there are few inverted lists.

More generally, you can store the index and see how big the file is.
