### ISSUE TITLE
train() vs. add() for IndexFlatL2 and IndexFlatIP

### ISSUE THREAD

**Issue by mabunday** [facebookresearch/faiss#2436]
I saw there was a previous question on this https://github.com/facebookresearch/faiss/issues/2209 but I didn't fully understand the linked answer: https://github.com/facebookresearch/faiss/wiki/Faster-search

1. What's the difference, if any, between using train() vs. add() when the index type is IndexFlatL2 or IndexFlatIP?

Are these two equivalent?
```python
index = faiss.IndexFlatIP(2000)
index.train(data)
```

```python
index = faiss.IndexFlatIP(2000)
index.add(data)
```

2. As an extension, if I have 4 machines and I'm trying to sample 2 billion points of data, are these three equivalent? 

```python
index = faiss.IndexFlatIP(2000)
index.train(data_all_two_billion_samples)
```

```python
index = faiss.IndexFlatIP(2000)
index.add(data_all_two_billion_samples)
```

```python
index = faiss.IndexFlatIP(2000)
# Each machine samples half a million data points. The master machine trains the index, then adds data from
# peer machines
index.train(data_machine_one_one_fourth_sample)
index.add(data_machine_one_one_fourth_sample)
index.add(data_machine_two_one_fourth_sample)
index.add(data_machine_three_one_fourth_sample)
index.add(data_machine_four_one_fourth_sample)
```

**Comment by Nimishbansal-16** [comment]
@mabunday Hey, did you get an answer to this? If yes, can you please help me as well, i am stuck wondering over the same thing

**Comment by Warmchay** [comment]
> @mabunday Hey, did you get an answer to this? If yes, can you please help me as well, i am stuck wondering over the same thing

I'm not sure am I right, I think after using `index.train()`, it will just left centroid vector, but using `index.add()`, it will left all the added vectors.

**Comment by balaramganesh** [comment]
From https://github.com/facebookresearch/faiss/wiki/Faster-search, what I've understood is this:
We can perform a flat search, that is, run over all the database vectors to find the nearest neighbors using any metric (Euclidean distance, inner product, cosine similarity). This does not require any "training". Hence, we can "add" all the vectors we want to search over directly to the index. 
In the case of optimized search (using quantization), FAISS uses composite indexes for this. That is, on top of the regular flat search index, additional indexes are present to perform quantization, and this requires training. For this purpose, we can either use a vector set that is representative of the database vectors, or all the database vectors itself to train the additional indexes. Once this is done, we can add the database vectors to the composite index. 
You can think of this as training an ML model to understand the distribution of the database vectors to give you the approximate nearest neighbors for a query vector. Once a composite index is trained, new vectors can be added to the database and the index without training the index. However, if we keep adding to the index indefinitely without any retraining, then the recall of the index will keep going down. So, it's necessary to retrain the index periodically. 

@mabunday, in the 1st situation, train method does nothing since you're using a flat index based of inner product. The add method on the other hand adds the vectors to the index. So, when you query this index, you'll get the exact nearest neighbors. 
In the 2nd situation, again, you're using a flat index. So, the train method does nothing, whether you train with the full or 1/4th dataset. However, the add method across all the 2 million vectors at once adds the vectors to the index, and adding them in 4 separate chunks makes no difference. Searching across both the indexes would perform a flat search for the exact nearest neighbors over 2 million vectors.
