### ISSUE TITLE
Why sometimes the ID returned was -1

### ISSUE THREAD

**Issue by zh454771942** [facebookresearch/faiss#244]
When I run the FAISS with IndexIVFPQ, sometimes the ID it returned are all -1. I have 4M data set, with 65536 training data. When I set nList = 1000, nProbe = 1 to search k = 32 nearest neighbors, I got all -1 IDs. If I change nList to 100, I would not have this issue. Could anyone explain why it happened?

**Comment by wickedfoo** [comment]
Did you get all -1 indices, or just some -1 indices?

-1 can occur if (a) the query vector contained garbage (NaNs), or (b) there was imbalance in the k-means used for partitioning the IVF, such that fewer than k vectors in the database were assigned to that particular list.

Basically, IVF splits the dataset of size N into nlist hopefully equal sized buckets of size N / nlist. However if there is imbalance, some buckets could have a lot more than N / nlist or a lot fewer.

nprobe controls how many of the buckets we look into to find candidate nearest neighbors. nprobe == 1 means we only look at the closest bucket.

However, for a 4M sized data set, having 32 -1s for k == 32 is worrying, since 32 is a lot smaller than 4000 ( = 4000000 / 1000).

**Comment by wickedfoo** [comment]
Also, is this with the L2 or IP metric? If IP, are you normalizing your input data and enabling spherical clustering upon training?

**Comment by zh454771942** [comment]
Thanks so much for your quick response. It is with L2 metric, and the indices returned are all -1, which gives me 0 recall. To make my question clear, when nlist = 100, nprobe = 1/10/50 works fine, but if I set nprobe = 100, it gives me 0 recall. I don't quite understand why increasing nprobe could lead to all -1 indices, since I have visited all cells, and why is the case when k = 32 is a lot smaller than 4000 should be worrying.
