### ISSUE TITLE
IDMap adds embeddings with repeated ids

### ISSUE THREAD

**Issue by javiabellan** [facebookresearch/faiss#2566]
## Summary

I would like to know if already exists a way for inserting and retrieving embeddings with repeated ids.

## User case:

At search time:
- `index.search(embedding, k=1000)`: Top 1000, unique, custom ids are returned
- `index.range_search(embedding, thresh=0.25)`: Filtered, unique, custom ids are returned

Both functions can be optimized under the hood by not looking at all the embeddings of same group ID if there is an embedding that already is a match with the query embedding.

## Reproducibility

I don't know if this is the default behaviour when i do the following:

```python
index = faiss.index_factory(512, "IDMap,L2norm,Flat", faiss.METRIC_INNER_PRODUCT)

embs = np.random.normal(size=(10,512)).astype("float32")
ids = np.array([1,2,2,3,3,3,4,4,5,1], dtype="int64")
index.add_with_ids(embs, ids)

query_emb = np.random.normal(size=(1,512)).astype("float32")
D, I  = index.search(query_emb, k=3) # sanity check
```

**Comment by mdouze** [comment]
It is not supported. 
For most Faiss use cases, ids are distinct.
Among the cases where they are not (eg. because they are class ids in k-NN classification), it is still beneficial to keep all the ids because they can be used to weight classes. 

Therefore, the use case with deduplicated ids seems marginal.
