### ISSUE TITLE
sub-quantizer

### ISSUE THREAD

**Issue by yja1** [facebookresearch/faiss#269]
in "demo_ivfpq_indexing_gpu.cpp" I want change dimension of the vectors to index. in the code is 
---------
int d = 128;
---------
when i set int d = 256; or other values,the error is 
-------------
terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at GpuIndexIVFPQ.cu:473: Error: 'ivfpqConfig_.usePrecomputedTables || IVFPQ::isSupportedNoPrecomputedSubDimSize( this->d / subQuantizers_)' failed: Number of dimensions per sub-quantizer (64) is not currently supported without precomputed codes. Only 1, 2, 3, 4, 6, 8, 10, 12, 16, 20, 24, 28, 32 dims per sub-quantizer are currently supported with no precomputed codes. Precomputed codes supports any number of dimensions, but will involve memory overheads.
Aborted (core dumped)
-------------

I set usePrecomputed(true) or usePrecomputed(false) both occur the same error.

**Comment by jegou** [comment]
As stated in the message error, it is because the number of dimension that each subquantizer needs to handle is not supported in the optimized mode.

You can address this by
- *typical:* increasing the number of subquantizers (parameter `M ` or `Subquantizer` I think). This is probably what you want to do because, anyway, the performance will not be decreasing if you increase the dimensionality without giving more bytes per vector
- reduce the vector dimensionality
- use the pre-computed tables

**Comment by reshu-b7** [comment]
Hi @jegou @yja1 

I am trying to perform knn search on a base set of 100M vectors of d = 100 (float32). I have able to successfully run various indexing methods (IVF096,PQ10/20/50, IVF16384,PQ10/20/50, OPQ10/20/50, etc. ) But when I try running the same indexing techniques using [bench_gpu_1bn.py](https://github.com/facebookresearch/faiss/tree/master/benchs) I run into the following error for PQ10, 20 and 50.

```
python bench_gpu_1bn.py dataset IVF4096,PQ50 -nnn 100 -ngpu 4 -tempmem $[2000*1024*1024]

Traceback (most recent call last):
  File "bench_gpu_1bn.py", line 745, in <module>
    index = get_populated_index(preproc)
  File "bench_gpu_1bn.py", line 617, in get_populated_index
    gpu_index, indexall = compute_populated_index(preproc)
  File "bench_gpu_1bn.py", line 528, in compute_populated_index
    vres, vdev, indexall, co)
RuntimeError: Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at GpuIndexIVFPQ.cu:439: Error: 'IVFPQ::isSupportedPQCodeLength(subQuantizers_)' failed: Number of bytes per encoded vector / sub-quantizers (50) is not supported
```

Being a 100d vector dataset, PQ10/20/50 are some of the best combinations that I can try experimenting on. Can you please shed some light on this ?

Thanks

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/blob/master/gpu/impl/IVFPQ.cu#L71

are the supported sizes. Ideally the size should be a power of 2 less than 32 (1, 2, 4, 8, 16, 32), otherwise the global memory loads are non-contiguous and will be slow.

20 currently appears to be supported, and I think we could support 10 or 50 as well, but the way this works in practice is that we will load 16 or 24 or 64 bytes and throw a lot of the data away.

The sizes supported need to be known at compile time, because dynamic loop indexing is very slow on the GPU.

**Comment by csldali** [comment]
It will be feasible to update faiss GPU, version 1.6.5 or later
