### ISSUE TITLE
Expose IDSelector filtering through c_api

### ISSUE THREAD

**Issue by kaelen-moda** [facebookresearch/faiss#2727]
I was wanting to play around with subset filtering on my searches using some go bindings against the [c_api](https://github.com/facebookresearch/faiss/tree/main/c_api).

Unfortunately, it doesn't seem like the [search header](https://github.com/facebookresearch/faiss/blob/main/c_api/Index_c.h#L103) is fully in line with the [internal implementation](https://github.com/facebookresearch/faiss/blob/main/faiss/Index.h#L124-L130) that exposes SearchParameters which contains the IDSelector filter.

Am I missing something obvious or are these out of sync? Is there a particular issue that is preventing the c_api from being in sync? The optional params? Would something like faiss_Index_search_w_params be doable here? 

https://github.com/facebookresearch/faiss/pull/2483

**Comment by Enet4** [comment]
> Is there a particular issue that is preventing the c_api from being in sync?

The issue is that the process of synchronizing the C API is purely manual and depends on volunteer work. The additional parameter in `search` was only introduced five months ago. With that said, a new function with the extra parameter would be doable and welcomed, so long as the `SearchParameters` and ID selector types are also given their C version in the API.

**Comment by kaelen-moda** [comment]
Thanks for the fast reply @Enet4! I worked on the implementation and submitted PR here: https://github.com/facebookresearch/faiss/pull/2732 

Happy to take some C/C++ style pointers as I'm pretty rusty  (puns not intended but welcome) :)
