### ISSUE TITLE
How to improve Faiss Performance

### ISSUE THREAD

**Issue by robbespo00** [facebookresearch/faiss#2812]
# Summary

What's the best way to maximize the Faiss performance during query time. In particular I am building an IndexIVFFlat

# Platform

OS: Ubuntu 22.04.2

Faiss version: 1.7.3

Installed from: using `cmake`

Faiss compilation options: `-DFAISS_ENABLE_GPU=OFF`   `-DFAISS_ENABLE_PYTHON=OFF` and it is used the MKL library

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by alexanderguzhva** [comment]
Please check https://github.com/facebookresearch/faiss/wiki/How-to-make-Faiss-run-faster, maybe you'll find something relevant
Also, please try the current master branch, because we're constantly publishing performance-related commits. 
It would be helpful if you could share some details of your dataset and the query batch sizes.
Thanks!

**Comment by robbespo00** [comment]
The dataset I'm using is Sift 1M and for the batch sizes I have tried different of them ranging from 10 up to 10'000.

**Comment by mdouze** [comment]
You may be interested in https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors
