### ISSUE TITLE
Obtaining cosine similarity

### ISSUE THREAD

**Issue by kumon** [facebookresearch/faiss#284]
Hi.
When we use IndexIVFFlat with METRIC_INNER_PRODUCT option, we can obtain cosine similarity. How about for IndexIVFPQ? Is there any ways to get the value?
I want to use the similarity to know how similar they are

**Comment by mdouze** [comment]
Hi 
You can set the metric_type field to METRIC_INNER_PRODUCT after the object is constructed, this should work.
Two remarks: 
- you can normalize the vectors before indexing and use L2 distance. Since distance_L2 = 2 - distance_inner_product the two are equivalent
- IVFPQ produces approximate distances, so the estimate may be imprecise.

**Comment by jegou** [comment]
Note that the strategy that Matthijs mentions would provide you very rough approximations of the inner product, because vectors quantized with PQ/IVFPQ have different norms, even if they are normalized prior to quantization. 

We have not implemented the version that would provide a better estimator of the cosine directly from the quantized codes (this is possible, pull request welcome). We would do if we have an important use-case, but for normalized vectors (our typical case) we had no need of that until now, since a simple turn-around is to make the search w.r.t. L2 distances and then use the function `search_and_reconstruct` to refine the similarity estimates on the top candidates.

**Comment by kumon** [comment]
Hi.
I use this library for image retrieval. I don't want to show any results if there is no similar images. For the purpose I use IndexIVFFlat with a threshold based on cosine similarity.
In order to handle more images in one server, I am considering using IndexIVFPQ. That is why I need to calculate cosine similarity to exclude not similar images from results.
I will try to use the approximate value for the threshold.
Thank you very much.

**Comment by jrcavani** [comment]
@jegou I know this question and answer were provided 5 years ago but have things changed since then?

If the answer still holds, it would be search with `IndexIVFPQ` and `METRIC_INNER_PRODUCT` is less accurate as `METRIC_L2`, even for normalized vectors. Does that sound right?

In addition do the reconstructed vectors from `IndexIVFPQ` `reconstruct()` or `search_and_reconstruct()` using a `METRIC_INNER_PRODUCT` suffer from the same imprecision compared with one with `METRIC_L2`?
