### ISSUE TITLE
polysemous_ht in GpuIndexIVFPQ

### ISSUE THREAD

**Issue by Liao1** [facebookresearch/faiss#286]
I find codes below in GpuIndexIVFPQ.cu
```
96  FAISS_ASSERT(index->pq.byte_per_idx == 1);
97  FAISS_ASSERT(index->by_residual);
98  FAISS_ASSERT(index->polysemous_ht == `0);`
```
why GpuIndexIVFPQ does not support `polysemous_ht`?

**Comment by jegou** [comment]
The polysemous codes are a strategy that is useful for CPU, but not for GPU. 

The reason is that, if only 1 of the process in a warp (out of, say, 32), have a positive test according to Hamming threshold, then the full wrap computing capability is used/wasted, irrespective of the number of positive/negative remaining tests. 
Therefore @wickedfoo has not implemented it. The same conclusion would hold for many filtering strategies based on distance.
