### ISSUE TITLE
FAISS taking long time to add to index for 30MB csv file

### ISSUE THREAD

**Issue by ompanda** [facebookresearch/faiss#2997]
FAISS is taking around 12hrs to create embedding and add it to index for 100000 rows csv file. is there any bulk load strategy for CSV files embeddings

**Comment by mlomeli1** [comment]
hi @ompanda, the faiss library does not have the functionality to create embeddings. My suspicion is that you are talking about the Langchain wrapper to faiss but I can't know for sure since you have not included some minimal working example and/or code pointers. Please do so, otherwise it's not possible for us to answer.

**Comment by mlomeli1** [comment]
Please direct these questions to the langchain, here is the link for your reference:

https://github.com/langchain-ai/langchain
