### ISSUE TITLE
How to add data with ids in IndexPQ

### ISSUE THREAD

**Issue by robbespo00** [facebookresearch/faiss#2998]
# Summary

Hi there I am working with `IndexPQ` and I need to add some data to the index using their ids. I tried to use the function `add_with_ids()` , but I get the following error "add_with_ids not implemented for this type of index". Below I report the code I have used.

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```python

import faiss

index = faiss.IndexPQ(d, m, nbits)
index.train(training_embeddings)
index.add_with_ids(doc_embeddings, doc_ids)
```

**Comment by guillaumeguy** [comment]
It's easy to keep the metadata in a separate DataFrame (along with all the entity metadata). You should consider it.

**Comment by mlomeli1** [comment]
hi @robbespo00 , please see our wiki about the indexes that support `add_with_ids`: https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing
the TLDR is that IndexPQ doesn't support that directly so you need to use it in the following way (this example is a tiny modification from the one in the wiki using IndexPQ instead of IndexFlatL2):

````
import faiss
import numpy as np
dimension = 16  # dimensions of each vector
n = 10000  # number of vectors
db_vectors = np.random.random((n, dimension)).astype("float32")
index = faiss.IndexPQ(db_vectors.shape[1],8,8) 
ids = np.arange(db_vectors.shape[0])
index.train(db_vectors[:400,:])
#index.add_with_ids(db_vectors, ids)  # this will crash, because IndexPQ does not support add_with_ids
index2 = faiss.IndexIDMap(index)
index2.add_with_ids(x=db_vectors,ids=ids) # works, the vectors are stored in the underlying index
````
