### ISSUE TITLE
is indexShards support concurrent query

### ISSUE THREAD

**Issue by GuoHaiQiang** [facebookresearch/faiss#321]
I know index support concurrent query, but i doubt whether indexShards support concurrent query.
`   index_shards = faiss.IndexShards(feature_dim, True, False) 
    for sub_index in indexes:
        index_shards.add_shard(sub_index)`
when i concurrent execute the operation
`D, I = index_shards.search(np.array(feature_array), nearest_count)`
it throw exception
`Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:147`

**Comment by mdouze** [comment]
Hi 
I don't thing GPU Faiss indexes support concurrent queries.

**Comment by GuoHaiQiang** [comment]
Can searches and additions be performed concurrently form several threads?

Concurrent searches are supported. Concurrent search/add or add/add are not supported. There is no locking mechanism in place to protect against this, but it is easy to maintain a lock in the calling code.

from the wiki, it says that Concurrent searches are supported.

**Comment by GuoHaiQiang** [comment]
@mdouze I also want to know what is the reason cause 
`Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:147`
thanks

**Comment by wickedfoo** [comment]
Faiss by default is not thread-safe. The restrictions are:

- a single index (CPU or GPU) can only be used by a single CPU thread at any given time.
- any GPU index that uses the same GpuResources object can only be use used by a single CPU thread at any given time. Since the GpuResources allocates a bunch of temporary memory on the GPU, this typically means that only one index per GPU can be used at any given time.

The error you are seeing is due to two CPU threads attempting to use the same GPU temporary memory allocation at the same time.

IndexShards is simply a multi-threaded wrapper around individual indices. It itself cannot be accessed from multiple threads at the same time.

Batching queries together is more performant that attempting to concurrently search from different threads in any case.

**Comment by AmierCheng** [comment]
I have the same problem。 How to solve this problem? Thanks！
Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at utils/StackDeviceMemory.cpp:147

@wickedfoo @mdouze @GuoHaiQiang

**Comment by beauby** [comment]
@AmierCheng Please refrain from pinging people when you have an open issue (#852) in which we are expecting further information from you to help narrow down your issue.

**Comment by wickedfoo** [comment]
The reason that assertion is happening is because you are using a single GpuResources object concurrently from more than one thread.

**Comment by yangp725** [comment]
> IndexShards is simply a multi-threaded wrapper around individual indices. It itself cannot be accessed from multiple threads at the same time.

Hi wickedfoo! Can IndexShards retrieve the multiple individual Indices concurrently?
