### ISSUE TITLE
remove_ids not affect, and always delete the last one

### ISSUE THREAD

**Issue by suyu15** [facebookresearch/faiss#3281]
# Summary
![9083e5bb-4fe3-4f38-b507-3b62178f7d66](https://github.com/facebookresearch/faiss/assets/31534687/7d2c6090-37e0-43c6-895e-a3b34bba239f)
        index = faiss.read_index(persistentPath + os.sep + indexName + '.faiss')
        index.remove_ids(np.array([175]))
        index.remove_ids(np.array(['175']))
        faiss.write_index(index, persistentPath + os.sep + indexName + '.faiss')
remove_ids not affect, and always delete the last one
And I try the str and int all  were not affected.

# Platform

OS: windows 11

Faiss version: 1.7.4

Installed from:  pip install

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions

![image](https://github.com/facebookresearch/faiss/assets/31534687/bd854090-686f-457b-8669-a629e997e132)

**Comment by mlomeli1** [comment]
From the screenshot, it looks like you are using Langchain @suyu15 . The langchain library advises to install faiss via pip install, however, the faiss library (us) do not support installs via pip (even when it is possible). In order to see whether this problem comes from the core faiss library, I would recommend first to create a clean conda environment and install faiss via conda as per the [INSTALL.md](https://github.com/facebookresearch/faiss/blob/547fe78c683465a52389d36f1bcac9f4f7543f9a/INSTALL.md) therein. Then, create a small repro example where you do not use langchain at all but just the core faiss library (from index creating to adding and removing ids). If that still fails, feel free to post it here and we can help. If you are following this path, please do not include Langchain in your env. Otherwise, please post your issue in the langchain git repo : https://github.com/langchain-ai/langchain
