### ISSUE TITLE
Can't run on the MacOS

### ISSUE THREAD

**Issue by brendon-ribeiro918** [facebookresearch/faiss#3605]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by AbduNG** [comment]
Writing to confirm this is true on my end as well. Refer to the below code:
`embedding_model_name = "BAAI/bge-small-en-v1.5"
dir_name = "BGE"

embedding_model = SentenceTransformer(embedding_model_name)
# Generate a dummy embedding to get the vector dimensionality
dummy_sentence = ["This is a dummy sentence."]
dummy_embedding = embedding_model.encode(dummy_sentence)

# Get the dimensionality of the embeddings
vector_dimensionality = dummy_embedding.shape[1]

# Save the model locally
embedding_model.save(dir_name)

# An index to enable quick similarity matching between vectors
faiss_index = faiss.IndexFlatL2(vector_dimensionality)
# The vector store where the embeddings are kept
vector_store = FaissVectorStore(faiss_index=faiss_index)
# Orchestrates the interation between the index and the vector store
storage_context = StorageContext.from_defaults(vector_store=vector_store)
# Takes chunks, embeds them, then organizes them into the vector store using the storage context as a definition of storage strategies
index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)

# Store the embeddings locally so we don't needd to calculate them every time
index.storage_context.persist()`

Running this in Jupyter Notebook would cause the kernel to crash without any explanation, I was getting `ExitCode: Undefined, Reason: `.

I tried:

- Clearing MPS cache around the problematic code
- Changing package versions
- Using code without virtual environment
- Using different Python versions

After isolating the issue through checking the imports, it turns out the the FAISS library import being present and using the LlamaIndex utilities or the sentence_transformer library caused this strange crash, I changed to ChromaDB and everything works fine now. Very weird bug.

P.S. This occurred both on Apple Silicon and a MacBook with an Intel chip.

**Comment by brendon-ribeiro918** [comment]
Thanks!
