### ISSUE TITLE
Time complexity for searching in a subset

### ISSUE THREAD

**Issue by acphile** [facebookresearch/faiss#3697]
# Summary

Hi, I want to understand the time complexity for searching in a subset https://github.com/facebookresearch/faiss/wiki/Setting-search-parameters-for-one-query#searching-in-a-subset-of-elements . Suppose `n` is the size of the overall index and `k` is the size of the subset. Is the time complexity independent of `n` (only related to `k`) or still affected by `n`

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
In general, the time complexity is still n because all the  vectors are searched and tested. 
There are few cases where the code can automatically restrict the search range, for example with an IDSelectorRange on an IndexFlat. 
See 
https://github.com/facebookresearch/faiss/wiki/Setting-search-parameters-for-one-query#idselectorrange

**Comment by kuarora** [comment]
Please see time complexity - https://github.com/facebookresearch/faiss/wiki/Setting-search-parameters-for-one-query#time-complexity
