### ISSUE TITLE
GPU memory usage even after deleting the index 

### ISSUE THREAD

**Issue by JoaoGuibs** [facebookresearch/faiss#3784]
# Summary

When using faiss on the GPU (flat index in this example), if we have an GPU OOM error, even after resetting and deleting the index, we still have some GPU memory being used (nvidia-smi screenshot below). Is this expected? If yes what are the reasons for this to happen?

Thanks in advance.

# Platform

OS: 

Faiss version: faiss-gpu, version 1.7.2

Installed from: pip

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

While running the following code, the memory usage on the breakpoint is shown below:

```
import torch
import faiss

def create_index(data):
    dimension = data.shape[1]
    index_flat = faiss.IndexFlatL2(dimension)
    gpu_resources = faiss.StandardGpuResources()
    gpu_options = faiss.GpuClonerOptions()
    device = torch.device("cuda")
    device_index = device.index
    gpu_options.device = device_index if device_index is not None else 0
    
    index = faiss.index_cpu_to_gpu(
        gpu_resources, gpu_options.device, index_flat, gpu_options
    )

    return index

data = torch.zeros((2950000, 1000))
index = create_index(data)

try:
    index.add(data)
except Exception as e:
    print(e)
    index.reset()
    del index
    breakpoint()
```

![image](https://github.com/user-attachments/assets/83eeff6a-693f-473f-866f-e15f5343b418)

**Comment by junjieqi** [comment]
Hi @JoaoGuibs, I tried to reproduce the issue by just using Faiss since I'm not familiar with torch. Here is the script I used 

```
import numpy as np
import faiss

d = 1000
nb = 2950000

rs = np.random
xb = rs.rand(nb, d).astype("float32")

index_flat = faiss.IndexFlatL2(d)
gpu_resources = faiss.StandardGpuResources()

index = faiss.index_cpu_to_gpu(gpu_resources, 0, index_flat)
try:
    index.add(xb)
except Exception as e:
    print(e)
    index.reset()
    del index
    breakpoint()
```

Here is the output from my local. I didn't notice the same result as you. Would you like to give a try?
<img width="628" alt="Screenshot 2024-08-22 at 1 19 05 PM" src="https://github.com/user-attachments/assets/e704f729-fde0-445b-a902-88771d767464">

**Comment by JoaoGuibs** [comment]
Thanks for the reply @junjieqi .
I realised I did not have added the line `import faiss.contrib.torch_utils` otherwise it errors with a different exception. Nonetheless I cannot reproduce your results by adding the garbage collection neither the cache clearing of torch. Would you mind telling me which faiss version are you using?

**Comment by junjieqi** [comment]
@JoaoGuibs  I think it is more related with python lifecycle management instead of the Faiss, as you can tell if you kill the python process, the memory will get cleared. I'm not sure if the python process will continue showing in the nvidia-smi command or not. I thought it only showed when the process was ongoing. However, after I finished the run, it should not show again.
