### ISSUE TITLE
How to compare sub vector codes in FAISS IndexIVFPQ

### ISSUE THREAD

**Issue by ashleyabraham** [facebookresearch/faiss#3844]
I have a use case where I need to compare a given query vector's PQ code to the results PQ codes to see how many sub vectors match. I use M=5, where M is the # of sub vectors, I am expecting the encoded codes to have 5 centroids, but when I use sa_encode I get more than 5, I think it is from the IVF or includes IVF. Is `sa_encode()` the right way to encode to compare sub vector to see how many of them match. I tried index.pq.compute_codes() and index.pq.decode() the recall error rates are too big. The sa_encode and sa_decode recall rates are so much better. Appreciate any help! Thanks

**Comment by mengdilin** [comment]
The official API for encoding and decoding is via `sa_encode` and `sa_decode`. See wiki for examples of usage: https://github.com/facebookresearch/faiss/wiki/Vector-codecs

You are right, the reason returned codes from IVFPQ differs from `M` is due to the fact that we prepend the centroid id in front of the code. This is why you should always use `sa_encode` and `sa_decode` side-by-side so you don't have to worry about internal details like this.

**Comment by ashleyabraham** [comment]
I don't have it in a repo, here is small output from my index (VF132000_HNSW32,PQ5x8) for one vector, encoded and decoded using stand alone and index.pq and the RMSE


```
import numpy as np

original_vec =np.array([[0.12048193, 0.13095239, 0.125     , 0.11363637, 0.09302326,
        0.28      , 0.3       , 0.35      , 0.36      , 0.39      ,
        0.7126437 , 0.68604654, 0.654321  , 0.64634144, 0.        ]],
      dtype=np.float32)

pq_coded = np.array([[162, 228, 129,  99, 200]], dtype=np.uint8)

pq_decoded = np.array([[ 0.02001748,  0.02764778,  0.02120071,  0.02097177,  0.02948603,
         0.02225134,  0.02371438,  0.01693289,  0.02033929, -0.00806424,
         0.02467275,  0.02808138,  0.01740647,  0.03190994,  0.        ]],
      dtype=np.float32)


sa_coded = np.array([[ 14,  62,   1,   9, 182,  38, 157, 111]], dtype=np.uint8)

sa_decoded = np.array([[0.11888802, 0.13124177, 0.12423619, 0.11237462, 0.09419049,
        0.27852243, 0.3014127 , 0.35024428, 0.36189026, 0.3899948 ,
        0.71050054, 0.68613887, 0.6542764 , 0.6461917 , 0.        ]],
      dtype=np.float32)

def calculate_rmse(y_pred, y_true):
  mse = np.mean((y_pred - y_true) ** 2)
  rmse = np.sqrt(mse)
  return rmse

print('PQ RMSE:', calculate_rmse(pq_decoded, original_vec)) #0.3882523

#stand Alone
print('SA RMSE: ', calculate_rmse(sa_decoded, original_vec)) #0.0011135458
```
```
PQ RMSE: 0.3882523
SA RMSE:  0.0011135458
```

**Comment by mengdilin** [comment]
It looks like the recall difference comes from encoding and decoding by residual. By default, IndexIVFPQ will encode/decode by residual while encoding directly with PR always means not by residual.

You can get the same recall when you turn off residual
```
index = faiss.IndexIVFPQ(quantizer, dim, nlist, m, 8)  # 8 bits per subquantizer
index.by_residual = False
```

**Comment by mdouze** [comment]
In IVFPQ, the PQ encodes the residual, which is the vector relative to the centroid it is assigned to (unless `by_residual` is set to false), see [Product quantization for NN search](https://inria.hal.science/inria-00514462/file/jegou_pq_postprint.pdf), IV.C. This is generally more accurate than directly encoding the vector with the PQ. 
In this case, it is incorrect to apply PQ to the vectors themselves because the PQ was trained to handle residuals, so it results in a high reconstruction error. 
Calling `sa_encode` / `sa_decode` generates PQ codes prefixed with the centroid id encoded on 2 bytes (thus sa_coded is also larger than pq_coded)

**Comment by ashleyabraham** [comment]
That makes sense, appreciate the clarification, thank you!
