### ISSUE TITLE
Release request: Could we get an updated release that builds on MacOS?

### ISSUE THREAD

**Issue by sarahec** [facebookresearch/faiss#3846]
# Summary

I'm a maintainer over at NixOS and we have many packages that depend on faiss (directly or indirectly) , but are all broken on Darwin. I've tried to cherry-pick patches to no avail. Would you be able to release a point release that works on Darwin? That would enable support for hundreds of packages.

**Comment by mengdilin** [comment]
@sarahec which version of faiss are you on and is this for OSX x86_64 for OSX arm64? We release to conda forge every night for OSX arm64 (e.g. https://anaconda.org/pytorch/faiss-cpu)

**Comment by sarahec** [comment]
We are on release 1.8.0 (see [nixpkgs search](https://search.nixos.org/packages?channel=unstable&show=faiss&from=0&size=50&sort=relevance&type=packages&query=faiss)) and build for linux-{x86,arm64} and OSX (Darwin)-{x86,aarch64}

We're currently building from source and that's our preferred way. Also, we prefer published source releases, which is why we're back on 1.8.0.

I understand the testing and other work that goes into making a release, so  my request may be a long shot. I had to try. :)

**Comment by mengdilin** [comment]
Is the x86 version failing or faiss compilation is failing for both? 

We have working nightly releases for OSX arm64 that runs on [macOS 14](https://github.com/actions/runner-images/blob/macos-14-arm64/20240903.5/images/macos/macos-14-arm64-Readme.md#macos-14) and part of that release compiles faiss from source and runs all of the relevent python tests along with it. If your issue is happening on OSX arm64, do you mind providing repro instructions when building and testing faiss from source?

**Comment by sarahec** [comment]
It's fine on x86, and breaking on macos. I'll try with the latest code on master and report back (thank you!).

**Comment by sarahec** [comment]
Yes, building from `master` works on both OSX and Linux.

**Comment by mengdilin** [comment]
We should be doing a release next week :) Will keep you updated

**Comment by sarahec** [comment]
You are amazing. Thank you.

**Comment by sarahec** [comment]
The work is still in progress, my silicon friend. Awaiting the next release.

**Comment by sarahec** [comment]
How is the release coming along, if I might ask?

**Comment by asadoughi** [comment]
I am working on the release this week in #3887

**Comment by sarahec** [comment]
Thank you!!
