### ISSUE TITLE
Meaning of PQ8+16

### ISSUE THREAD

**Issue by mucun1988** [facebookresearch/faiss#390]
While I am reading High level interface and auto tuning
(https://github.com/facebookresearch/faiss/wiki/High-level-interface-and-auto-tuning), I am a bit confused by the following statement on PQx+y refinement
`...with "PQ8+16", works only after an inverted file option, using 8 bytes stored in the inverted index and 16 bytes of refinement...`.

My understand is the that refinement is always based upon `coarse quantizer` which is learned during making inverted files. So is  `8 bytes stored in the inverted index ` redundant to specify? Basically, I do not quite understand the meaning of the refinement PQx+y...

Thanks,
Matt

**Comment by mdouze** [comment]
Hi 
PQ8+16 is an IndexIVFPQR, that was described in 
@inproceedings{jegou2011searching,
  title={Searching in one billion vectors: re-rank with source coding},
  author={J{\'e}gou, Herv{\'e} and Tavenard, Romain and Douze, Matthijs and Amsaleg, Laurent},
  booktitle={Acoustics, Speech and Signal Processing (ICASSP), 2011 IEEE International Conference on},
  pages={861--864},
  year={2011},
  organization={IEEE}
}
It is like an IVFPQ but after the search has been performed, the results are re-ranked by computing a better approximation of the vectors using 16 bytes of PQ.  We would not recommend using it for beginners because it is hard to tune.
