### ISSUE TITLE
"Dynamic" Nearest Neighbour searches possible?

### ISSUE THREAD

**Issue by LeanderK** [facebookresearch/faiss#446]
Is it possible to use `faiss` for a task where need to get the nearest neighbour that satisfies a certain criteria?

I don't know how many datapoints I would need for each input. So I would have to get a batch of `k` NNs, check if one of them satisfies the criteria and if not get the next batch. Do you expect drastic slowdowns when the size of `k` is large? Can I skip the first `n`?
It's also possible to evaluate the neighbours one by one, if that makes it easier.

EDIT: also the dimensionality is quite large and the dataset doesn't fit into the RAM 😀

**Comment by wickedfoo** [comment]
The best way to solve this using Faiss would be to start with a very large size of k, and just query once; if the vector you are looking for is not in the results, then tough luck. Faiss is largely memory bandwidth bound, so it is best to traverse all of the memory a single time, rather than doing it many times.

For CPU, `k` is practically unlimited, but ideally it should be small enough such that the heap fits into L1/L2. For GPU, `k` is limited to 1024 or less.

**Comment by beauby** [comment]
Closing this as the issue seems to be solved. Feel free to keep commenting if you have further questions.
