### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by sbdk82** [facebookresearch/faiss#54]
How could I use this as an library for my simple program where I am searching similar strings from a set of billion strings for a query string?

**Comment by jegou** [comment]
Faiss is not a string matching library. 
If you can cast your problem to vector search (i.e., by using string embeddings such as sums of word2vec), then you may consider Faiss, but the hard part will be to define a proper string embedding in the first place that would be adapted to your problem. Otherwise consider using a specific string matching algorithm.

**Comment by sbdk82** [comment]
How about converting the string to a vector of hash values of its q-grams?

**Comment by jegou** [comment]
@sbdk82 
This conversion is a way to define an embedding. 
Directly using a q-gram as a sum of 1-hot vector may be ok-ish but not taking into account the inter-word similarity. This is why I suggested taking the sum of word2vec (over q-grams for instance) instead.

**Comment by sbdk82** [comment]
@jegou Thanks !!

**Comment by Ashansl** [comment]
How can i use word2vev with FAISS
