### ISSUE TITLE
curse of dimensionality and faiss

### ISSUE THREAD

**Issue by iNDicat0r** [facebookresearch/faiss#57]
Hello

KNN by its nature suffers from curse of dimensionality, and my question is whether or not Faiss has done anything to 'improve' these kind of searches.

Regards

**Comment by jegou** [comment]
Please look at the benchmarks we provide on various kind of data:
https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors

which shows that indeed Faiss offers some improvement versus the previous solutions on typical data. Faiss is a library, so please read the papers cited in the wiki, which are the ones introducing the techniques themselves, such as the Polysemous codes. 

More generally, in my opinion the question is vague because an acceleration of exact search (like the one we propose in Faiss both for Exact distance calculation or approximate one with PQ) is actually the best way to fight the curse of dimensionality when the conditions are the worst, i.e,. for random data with D very high. 

Regards

**Comment by iNDicat0r** [comment]
Thanks for the prompt response.
What would you consider a high D ? I am talking about 2048 dimensions in my case..

**Comment by jegou** [comment]
The question is not really the (extrinsic) observable dimension, but the true internal complexity of the data. 2048 dimensions generated with rand or randn would be very high dimensional and you would need brute-force for that (such as IndexFlat, its GPU counterpart or IndexPQ/LSH). 
2048 dimensions coming from the real world (e.g., neural net features) is typically easy to index. Only empirical tests will tell you if you can index with non-exhaustive index, depending also on the desired accuracy/speed-up trade-off.

**Comment by iNDicat0r** [comment]
The dimensions are from neural net features, i will try to observe the performance based on different configurations.

**Comment by jegou** [comment]
If they are neural nets features, then they should be highly redundant and I would suggest to use the PCA pre-processing (available in Faiss).

**Comment by iNDicat0r** [comment]
Excelent! Thanks
