### ISSUE TITLE
Can pca transform be calculated by gpu?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#570]
I find the  pca_mat.apply_py() function is very cpu consuming.  
If i install the gpu version of faiss, will the apply_py() function use gpu instead of cpu to calculate vector result?

I find the apply_by() fucntion will grab all cpu resource for caculation. Can i limit the cpu resource it can use? I don't want it to consume all the cpu, which causes my server down.
@mdouze

**Comment by universewill** [comment]
Can i get the pca transform matrix from the faiss pca trained result? I think i can use tensorflow, pytorch or mxnet to calculate the matrix production if i can get the matrix from faiss pca trained result.

**Comment by mdouze** [comment]
The pre-transform routines are not implemented on GPU because they are usually not a bottleneck in the computation. If this is the case for you, you presumably use large input vectors. 

To get the PCA matrix, please do:

```
pca = PCAMatrix(...)
pca.train(...)
A = faiss.vector_to_array(pca.A).reshape(pca.d_out, pca.d_in)
b = faiss.vector_to_array(pca.b)
```
Then the equivalent of applying PCA to matrix `x` is
```
x_out = np.dot(x, A.T) + b
```
which you can translate to your favorite GPU matrix lib.
