### ISSUE TITLE
Does read_index_binary with memory leak?

### ISSUE THREAD

**Issue by nuaawzl** [facebookresearch/faiss#581]
# Summary
faiss.read_index_binary with memory leak?
# Platform
Ubuntu16.04

Faiss version: 0.1

Faiss compilation options: openblas

Running on: CPU

Interface: Python

# Reproduction instructions
```
def load(self, model_name):
    tmp_index = faiss.read_index_binary(model_name)
    return True
```

The ”load“ func is just a test. when I call it repeatedly, the memory leak and memory Gradually increasing. No error when read index, what can I do? thanks

**Comment by mdouze** [comment]
Is it an `IndexBinaryFlat` or and `IndexBinaryIVF` ?

**Comment by nuaawzl** [comment]
IndexBinaryIVF

**Comment by nuaawzl** [comment]
I also try to do this, but no use
> tmp_index.reset() 
> del tmp_index

 but no use

**Comment by nuaawzl** [comment]
Hello, when try test the function  by C++, no memory leak. Why? 
```
void IndexLoad(std::string fname)
{
    faiss::IndexBinary *index = faiss::read_index_binary(fname.c_str());
    std::cout << "Total: " << index -> ntotal << std::endl;
    delete index;
}
```

**Comment by mdouze** [comment]
It means the leak is at the python level, and more precisely that `read_index_binary` does not set the "own" flag of the pointer to 1. This should not happen since 
https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss.swig#L436
-> says that the output should be owned 
However, in swigfaiss_wrap.cpp

 `_wrap_read_index_binary__SWIG_0` ->` SWIG_NewPointerObj(..., 0) `

argument 0 means that it is *not* owned, ie the corresponding macro is called with $owned=0, when for `_wrap_read_index__SWIG_0` the  `$owned= SWIG_POINTER_OWN`.

This may be due to the order of declarations, does the `%newobject` appear before the include?

**Comment by ort55555** [comment]
read_binary_index newobject;

**Comment by nuaawzl** [comment]
Thank you for reply，do this?
`%newobject read_binary_index;  -> %read_binary_index newobject `

**Comment by nuaawzl** [comment]
I fixed the problem  by very ugly method based on the swig.
in index_io
```
void release_indexbinary(IndexBinary *index)
{
    if (index)
    {
        delete index;
        index = nullptr;
    }
}
```
in swigfaiss.swig
```
%newobject read_index;
%newobject read_binary_index;
+ %delobject release_indexbinary;
%newobject read_VectorTransform;
%newobject read_ProductQuantizer;
%newobject clone_index;
%newobject clone_VectorTransform;
```
Get the new swigfaiss.py and swigfaiss_wrap.cpp and install. It seems to solve this problem, but I'm not sure. 
Any suggestion? I'm sorry for my poor English. Thank you!

**Comment by beauby** [comment]
This will be fixed in the next release. Note that 1. it only affects `read_index_binary`, and 2. a simple workaround is to set the `thisown` flag to `True` on the returned index, i.e.
```python
index = faiss.read_index_binary(fname)
index.thisown = True
```
