### ISSUE TITLE
How to read the index from the disk fastly?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#629]
`faiss.read_index` is slow if the index file is large enough.

**Comment by mdouze** [comment]
`IndexIVF`s can be memory-mapped instead of read from disk, load with faiss.read_index flag `IO_FLAG_MMAP|IO_FLAG_READ_ONLY`. This is efficient if you need only to do a few queries or get some stats from the index. 

Apart from that, the index loading is as fast as the underlying storage. So faster if on SSD, faster if local disk, even faster the file is cached.
