### ISSUE TITLE
LSH read out indexes

### ISSUE THREAD

**Issue by oguitart** [facebookresearch/faiss#630]
Hi,

I'm using LSH to create the indexes. Is it possible to read out the binary indexes after the data is added? For instance, if I'm using nbits 32, I would like to get the 32 bit representation of each of the vectors from my input data.
Thanks,

oriol

**Comment by mdouze** [comment]
The encoded data is available as `index.codes`. You can convert it to numpy with 

`faiss.vector_to_array(index.codes).reshape(-1, index.nbits / 8)`

**Comment by oguitart** [comment]
Great thanks!

oriol

**Comment by chikubee** [comment]
@mdouze I am trying to compute the binary vector of the 192 Byte hash code, so that I can match them using Hamming distance and compute estimate number of buckets it is creating.
Which function can help me do that?

Like we give expected number of clusters here 
https://pypi.org/project/LocalitySensitiveHashing/
Why don't we do it with FAISS?
