### ISSUE TITLE
Search on GPU and output on GPU

### ISSUE THREAD

**Issue by turpaultn** [facebookresearch/faiss#725]
Hi,

Could it be possible to know if the example in [test_pytorch_faiss.py](https://github.com/facebookresearch/faiss/blob/master/gpu/test/test_pytorch_faiss.py) can run entirely on GPU, even the verification at the end of `test_raw_array_search(self)` ?

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
Actually the test_pytorch_faiss.py example has implicit synchronizations because the data is moved back to CPU. 
When staying on GPU, the synchronization is also needed because Faiss uses a non-default CUDA stream. The easiest workaround is to force it to use the default stream. For this you can set: 
```
res = faiss.StandardGpuResources()
res.setDefaultNullStreamAllDevices()
```
After instantiating the object. Also, by default the amount of memory allocated by the resource object is too large for simple brute force. You can set: 
```
res.setTempMemory(64 * 1024 * 1024)
```
ie. use only 64M (if that is not enough, try a few other values).

**Comment by mdouze** [comment]
Added a wiki entry about this: 
https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index

**Comment by beauby** [comment]
Closing, as the question was answered. Feel free to keep commenting should you need further help.
