### ISSUE TITLE
Another way to install with docker

### ISSUE THREAD

**Issue by jubenjum** [facebookresearch/faiss#77]
Hi,

In the "docker instructions" section in the INSTALL file, I think you can  also build the docker image by doing:

nvidia-docker build -t 'faiss' https://github.com/facebookresearch/faiss

then you won't need to clone all the repository. 

Juan

**Comment by mdouze** [comment]
Hi 

Thanks for the information. @pletessier, any comment about this?

**Comment by pletessier** [comment]
Hi,
That's true, I wasn't aware of this feature, thanks for the info @jubenjum ! Note that with my version of Docker (1.13.0), I was needed to remove the "protocol part" of the url to make it work. It seems to be the good syntax according to https://docs.docker.com/engine/reference/commandline/build/#build-with-url.
So the command was `nvidia-docker build -t 'faiss' github.com/facebookresearch/faiss`

But, by doing that, you still need to to bring the sources inside the container. Giving an URL in the build step of docker is just giving a build context. 

So the best way to build the image would probably be to ADD the sources from the context (URL or local path) rather than cloning a second time from github. It would also be easier to make changes in the code this way.

It would also be preferable to write an Ubuntu 16.04 dedicated makefile.inc to avoid the "dirty sed replacing" of the LDFLAGS vars.

I will take care of that in a few days if nobody took the ticket !

Pierre

**Comment by mdouze** [comment]
Seems to be taken into account. Closing issue.
