### ISSUE TITLE
Inconsistent result in "IVF256,PQ32" Index trained on CPU/GPU

### ISSUE THREAD

**Issue by chenyihang1993** [facebookresearch/faiss#802]
Hi, there,
I did an experiment, and it turned out to be a little strange. The search result of GPU index is not the same as CPU, even although on the same dateset with the same index. The code is

```import numpy as np
import faiss

d = 64  # dimension
nb = 100000  # database size
nq = 10000  # nb of queries
np.random.seed(1234)  # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

k = 4

# -----------------index------------------------
index = faiss.index_factory(d, "IVF256,PQ32")
index.train(xb)
index.add(xb)
D, I = index.search(xq, k)
# -----------------gpu index------------------------
base_index = faiss.index_factory(d, "IVF256,PQ32")
co = faiss.GpuClonerOptions()
res = faiss.StandardGpuResources()
gpu_index = faiss.index_cpu_to_gpu(res, 0, base_index, co)
gpu_index.train(xb)
gpu_index.add(xb)
gpu_D, gpu_I = gpu_index.search(xq, k)
```
The result is
```
[[6.854656  6.861514  7.2781086 7.5431404]
 [6.5061197 6.575661  6.6793814 6.9486547]
 [6.8964763 7.1543508 7.2369905 7.2891107]
 [5.600876  6.380968  7.0203857 7.4495077]]
[[381 207 210 588]
 [526 300 142 576]
 [527 425 637 281]
 [196 184 164 359]]
==================================
[[6.824486  7.049329  7.2617726 7.5390377]
 [6.6077976 6.6407022 6.711151  6.7137628]
 [6.905389  6.977456  7.2702103 7.366224 ]
 [5.68802   6.2579827 7.044121  7.2641616]]
[[381 207 210 477]
 [142 526 576  72]
 [527 281 425 637]
 [196 184 164 359]]
```
The result of the GPU index and CPU index are not the same.
Could you tell the cause of this problem and the solution? Thanks.
@mdouze @beauby @wickedfoo

**Comment by wickedfoo** [comment]
@chenyihang1993 In this case, the GPU and CPU are being trained separately. There are order of operations differences in floating-point matrix multiplication between MKL and cuBLAS and other differences, which would be magnified by the fact that the learned quantization schemes probably differ slightly (or even drastically) between CPU and GPU because they are independent trainings, so completely different IVF and PQ assignments (and IVF centroid / PQ centroid) vectors would be obtained between the two. The CPU and GPU implementations are not guaranteed to be bit-accurate to each other.

Product quantization on the residual vector is used here as well, so the reported distances would also differ if the underlying quantization is different, as the distance returned is an approximation using the PQ codes, not the true unquantized/uncompressed distance.

To compare the current setup, one would have to perform a search of some reasonably large top k (say, k = 50 or so) and find the overlap between the two returned sets, and how far out of order the two results are.

I would be more concerned if the data differs substantially if you train the CPU, and then before adding vectors, copy the CPU index to the GPU, then add both vectors. This should differ less (though could still differ on very marginal cases due to different IVF or PQ assignments due to floating point order-of-operations evaluation differences). 

What should differ the least (should be nearly exact) would be training and adding vectors to the CPU index, then copying that index over to the GPU and comparing there.

**Comment by wickedfoo** [comment]
this doesn't preclude there being a bug though, just that I would perform a deeper comparison with larger k and see how many differences are being reported between the two

**Comment by wickedfoo** [comment]
also nprobe = 1 likely here, a larger nprobe should be considered as well, as the IVF assignments could be completely different due to the separate trainings

**Comment by chenyihang1993** [comment]
I got it, Thank you.
