### ISSUE TITLE
mmap support in IndexIVFFlat ?

### ISSUE THREAD

**Issue by Cyloo** [facebookresearch/faiss#83]
As far as I know, there is mmap support only in IndexIVFPQCompact, so I wonder will there be mmap support in IndexIVFFlat in the future? (since IndexIVFFlat has a great performance both on speed and accuracy, I am planning using it in a multi-processing scenario.)

**Comment by mdouze** [comment]
Hi 

IndexIVFPQCompact is not really used, because faiss is used mainly in multithreading rather than multiprocessing scenarios. Note that faiss releases the GIL in Python, so multithreading works fine in Python too (see eg https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_1bn.py)

Therefore, it is unlikely that we will support mmapping for other indexes.
