### ISSUE TITLE
Question: Binary Vectors

### ISSUE THREAD

**Issue by danielcrane** [facebookresearch/faiss#86]
I currently have a database of binary hash codes in which I would like to perform an exact k-NN search (using Hamming distance) given a query binary hash code. I believe that using FAISS this could be achieved by providing `xb` as a matrix composed of binary vectors, and using the L2-norm as shown in the examples (which gives the same results for binary vectors if you square the returned distance).

As FAISS is made to use 32-bit integers, it occurs to me that in my case this would increase the required memory significantly, as each bit would be stored as a 32-bit integer.

As I noticed that several of the indexing methods do indeed use binary representations (i.e. LSH) to store and search within the database, I was wondering if there's any way to directly provide such a binary database directly to FAISS, or if there was any other recommendation that anyone could provide me with.

If FAISS is just not suited for my problem, then I completely understand, but I thought I'd ask before giving up!

**Comment by wickedfoo** [comment]
If you have a single query vector, then writing code to compare Hamming distances against a set of binary vectors is fairly easy, and it can be parallelized across the set of vectors. The comparison is likely memory bandwidth bound, and a fairly naive implementation in C/C++ would do OK.

For a batch of query vectors against a database set, for efficiency you'd want something that tiles the computation like a GEMM kernel to ensure memory reuse, but instead compares Hamming distance between binary vectors instead of R^k inner product.

There isn't anything really in Faiss that provides these, sorry. Converting the bits to floating point values seems like a huge waste (and increases the memory traffic by 32x).

**Comment by danielcrane** [comment]
Thank you for your response. Right now I'm indeed using a naive C implementation, and I was just exploring my options to see if there was anything better available (or even possible).

I appreciate your advice!

**Comment by wickedfoo** [comment]
I hope that the naive implementation uses a popcount hardware primitive, a truly naive version that does shifting and masking will be incredibly slow.

**Comment by mrgloom** [comment]
You can give it a try:
https://github.com/valbok/HEngine (Large Scale Hamming Distance Query Processing)

**Comment by jegou** [comment]
Faiss actually provides some computation of Hamming distance in compact format (64-bits vectors stored as `uint64_t`), for instance stored in the IndexLSH index on the CPU. The corresponding functions are defined in hamming.cpp 
No GPU implementation however. 
This Hamming distance computation is reasonably optimized, but as @wickedfoo mentioned there is no tiling (used to exist, good parameter for it can be seen in the remaining BLOCKSIZE_QUERY=8192 variable still defined in the code).
