### ISSUE TITLE
Faiss index_read method for large index file is extremely slow and taking a large amount of memory. 

### ISSUE THREAD

**Issue by XinliYu** [facebookresearch/faiss#909]
I am working with an Amazon cloud virtual machine with 64 cores and 500G memory. I installed the latest version of Faiss.

I have four 200G index files and I load each of them using `index_read`. It took hours and it is consuming 300G+ memory. **I am assuming Faiss is a database and should not take up so much memory. Is it because Faiss is caching the embeddings into the memory?**

Meanwhile, I would like to use mult-processing to search in parallel if the memory usage can be reduced. Is it OK to execute `index_read` in each sub-process and then do the search independently for each sub-process?

**Comment by Enet4** [comment]
Actually, Faiss is more of a dense vector index library, rather than a feature database. Which index type did you use? How large are the elements are in each of those 200G indexes? Most indexing algorithms require the full index to be in memory. You might wish to use a more memory-efficient index type.

**Comment by mdouze** [comment]
Faiss stores indexes in RAM, so your index will be copied to RAM by default. This may be a problem when disk I/O is slow, please make sure what the disk read speed is you can get on your platform.

Alternatively, some types of indexes (the IVF variants) can be memory-mapped instead of read in RAM, see 

https://github.com/facebookresearch/faiss/blob/3896b12c656826bcf3a6cb6ef1a35aa05549d861/tests/test_index_composite.py#L319

this makes loading the index faster but searching is slower.

Concurrent searches and loads are supported, see 

https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by XinliYu** [comment]
@mdouze Thanks! This explains the slow loading and large memory usage. The loading is almost instance after enabling the memory-mapped files.
