### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by bkj** [facebookresearch/faiss#91]
I'm working on building an image search capability, subject to the following restrictions.  I was wondering if anyone w/ more `faiss` experience may be able to give some guidance on the best architecture choices.

 1) indexing _stream(s)_ of 4096D CNN image descriptors
 2) need to scale to approx. 10 indices of approx. 20M image descriptors each
 3) only care about being able to retrieve the ~25 most similar images to a query
 4) queries will be processed one-by-one, rather than batched
 5) no access to GPUs
 6) queries come from users, so I only need "human scale" response times

A couple of notes:
  -  (1) means that I'll need to `.add()` data as it comes in -- does that mean I should stay away from methods that need `.train()`.  Presumably I could `.train()` on a large (enough) set of in-domain data, and the indices will remain performant as I `.add()` more data? 
  - I'll have to use either a) indices w/ enough compression to all fit in memory simultaneously, or b) indices that can be written/read from disk pretty quickly.

My first instinct is to use the LSH index, since it's fast, memory efficient, and (AFAIK) shouldn't degrade as new data is added.  But I'm no expert on the tradeoffs between the various methods, so any input would be much appreciated.

Thanks

**Comment by wickedfoo** [comment]
re: staying away from train, that's only an issue if the statistics of the dataset change over time. Otherwise, add for the new data should work well.

1. 4096D is a huge waste of computation, consider reducing the dimensions (PCA etc.) before adding to the index. cf Artem Babenko, Anton Slesarev, Alexandr Chigorin, and Victor Lempitsky. 2014. Neural codes for image retrieval.

2. why 10 indices? why not 1 index with 200M descriptors?

4. this will be in the regime where pretty much any index (Flat, IVFFlat, IVFPQ, LSH, ...) would be memory bandwidth bound, rather than compute bound. The less memory you touch, the better, therefore choosing an index with some first-level partitioning and sub-selection will work better.

**Comment by bkj** [comment]
Thanks for the quick response!  

(1) makes sense -- doing PCA first seems reasonable

(2) 10 indices because there are 10 separate data streams, and each query should only return results from the same data stream.

(4) Are there any examples in the wiki or benchmarks showing the "first-level partitioning + sub-selection"?  I'm not sure I understand exactly what that means

**Comment by mdouze** [comment]
@bkj, the "first-level partitioning" are all methods that begin with IVF. See 

https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_sift1m.py#L86

GPU not required, also works on CPU.
